Import packages to support loading data into a database table from a csv file

In [1]:
import pandas as pd
from sqlalchemy import create_engine

Load SQL extension

In [2]:
%load_ext sql

Connect to your sakila database on AWS RDS

In [3]:
%sql mysql://USERNAME:PASSWORD@HOST/DATABASE

### CTE Syntax

```
WITH cte1 AS (
SELECT col1, col2
	FROM table1
) 
SELECT col1, col2 
FROM cte1;
```

Use a CTE instead of a VIEW to create a list of active customers. Include the first_name, last_name, and an obscured email.  

First verify active_customer VIEW with a SELECT.

In [4]:
%%sql
SELECT *
FROM active_customer;

 * mysql://HOST:PASSWORD@HOST/DATABASE
584 rows affected.

[('MARY', 'SMITH', 'MA*****.org'),
 ('PATRICIA', 'JOHNSON', 'PA*****.org'),
 ('LINDA', 'KENNEDY', 'LI*****.org'),
 ('BARBARA', 'JONES', 'BA*****.org'),
 ('ELIZABETH', 'BROWN', 'EL*****.org'),
 ('JENNIFER', 'DAVIS', 'JE*****.org'),
 ('MARIA', 'MILLER', 'MA*****.org'),
 ('SUSAN', 'WILSON', 'SU*****.org'),
 ('MARGARET', 'MOORE', 'MA*****.org'),
 ('DOROTHY', 'TAYLOR', 'DO*****.org'),
 ('LISA', 'ANDERSON', 'LI*****.org'),
 ('NANCY', 'THOMAS', 'NA*****.org'),
 ('KAREN', 'JACKSON', 'KA*****.org'),
 ('BETTY', 'WHITE', 'BE*****.org'),
 ('HELEN', 'HARRIS', 'HE*****.org'),
 ('DONNA', 'THOMPSON', 'DO*****.org'),
 ('CAROL', 'GARCIA', 'CA*****.org'),
 ('RUTH', 'MARTINEZ', 'RU*****.org'),
 ('SHARON', 'ROBINSON', 'SH*****.org'),
 ('MICHELLE', 'CLARK', 'MI*****.org'),
 ('LAURA', 'RODRIGUEZ', 'LA*****.org'),
 ('SARAH', 'LEWIS', 'SA*****.org'),
 ('KIMBERLY', 'LEE', 'KI*****.org'),
 ('DEBORAH', 'WALKER', 'DE*****.org'),
 ('JESSICA', 'HALL', 'JE*****.org'),
 ('SHIRLEY', 'ALLEN', 'SH*****.org'),
 ('CYNTHIA', 'YOUNG', 'CY*****.org'),
 ('ANGELA', 'HERNANDEZ', 'AN*****.org'),
 ('MELISSA', 'KING', 'ME*****.org'),
 ('BRENDA', 'WRIGHT', 'BR*****.org'),
 ('AMY', 'LOPEZ', 'AM*****.org'),
 ('ANNA', 'HILL', 'AN*****.org'),
 ('REBECCA', 'SCOTT', 'RE*****.org'),
 ('VIRGINIA', 'GREEN', 'VI*****.org'),
 ('KATHLEEN', 'ADAMS', 'KA*****.org'),
 ('PAMELA', 'BAKER', 'PA*****.org'),
 ('MARTHA', 'GONZALEZ', 'MA*****.org'),
 ('DEBRA', 'NELSON', 'DE*****.org'),
 ('AMANDA', 'CARTER', 'AM*****.org'),
 ('STEPHANIE', 'MITCHELL', 'ST*****.org'),
 ('CAROLYN', 'PEREZ', 'CA*****.org'),
 ('CHRISTINE', 'ROBERTS', 'CH*****.org'),
 ('MARIE', 'TURNER', 'MA*****.org'),
 ('JANET', 'PHILLIPS', 'JA*****.org'),
 ('CATHERINE', 'CAMPBELL', 'CA*****.org'),
 ('FRANCES', 'PARKER', 'FR*****.org'),
 ('ANN', 'EVANS', 'AN*****.org'),
 ('JOYCE', 'EDWARDS', 'JO*****.org'),
 ('DIANE', 'COLLINS', 'DI*****.org'),
 ('ALICE', 'STEWART', 'AL*****.org'),
 ('JULIE', 'SANCHEZ', 'JU*****.org'),
 ('HEATHER', 'MORRIS', 'HE*****.org'),
 ('TERESA', 'ROGERS', 'TE*****.org'),
 ('DORIS', 'REED', 'DO*****.org'),
 ('GLORIA', 'COOK', 'GL*****.org'),
 ('EVELYN', 'MORGAN', 'EV*****.org'),
 ('JEAN', 'BELL', 'JE*****.org'),
 ('CHERYL', 'MURPHY', 'CH*****.org'),
 ('MILDRED', 'BAILEY', 'MI*****.org'),
 ('KATHERINE', 'RIVERA', 'KA*****.org'),
 ('JOAN', 'COOPER', 'JO*****.org'),
 ('ASHLEY', 'RICHARDSON', 'AS*****.org'),
 ('ROSE', 'HOWARD', 'RO*****.org'),
 ('JANICE', 'WARD', 'JA*****.org'),
 ('KELLY', 'TORRES', 'KE*****.org'),
 ('NICOLE', 'PETERSON', 'NI*****.org'),
 ('JUDY', 'GRAY', 'JU*****.org'),
 ('CHRISTINA', 'RAMIREZ', 'CH*****.org'),
 ('KATHY', 'JAMES', 'KA*****.org'),
 ('THERESA', 'WATSON', 'TH*****.org'),
 ('BEVERLY', 'BROOKS', 'BE*****.org'),
 ('DENISE', 'KELLY', 'DE*****.org'),
 ('TAMMY', 'SANDERS', 'TA*****.org'),
 ('IRENE', 'PRICE', 'IR*****.org'),
 ('JANE', 'BENNETT', 'JA*****.org'),
 ('LORI', 'WOOD', 'LO*****.org'),
 ('RACHEL', 'BARNES', 'RA*****.org'),
 ('MARILYN', 'ROSS', 'MA*****.org'),
 ('ANDREA', 'HENDERSON', 'AN*****.org'),
 ('KATHRYN', 'COLEMAN', 'KA*****.org'),
 ('LOUISE', 'JENKINS', 'LO*****.org'),
 ('SARA', 'PERRY', 'SA*****.org'),
 ('ANNE', 'POWELL', 'AN*****.org'),
 ('JACQUELINE', 'LONG', 'JA*****.org'),
 ('WANDA', 'PATTERSON', 'WA*****.org'),
 ('BONNIE', 'HUGHES', 'BO*****.org'),
 ('JULIA', 'FLORES', 'JU*****.org'),
 ('RUBY', 'WASHINGTON', 'RU*****.org'),
 ('LOIS', 'BUTLER', 'LO*****.org'),
 ('TINA', 'SIMMONS', 'TI*****.org'),
 ('PHYLLIS', 'FOSTER', 'PH*****.org'),
 ('NORMA', 'GONZALES', 'NO*****.org'),
 ('PAULA', 'BRYANT', 'PA*****.org'),
 ('DIANA', 'ALEXANDER', 'DI*****.org'),
 ('ANNIE', 'RUSSELL', 'AN*****.org'),
 ('LILLIAN', 'GRIFFIN', 'LI*****.org'),
 ('EMILY', 'DIAZ', 'EM*****.org'),
 ('ROBIN', 'HAYES', 'RO*****.org'),
 ('PEGGY', 'MYERS', 'PE*****.org'),
 ('CRYSTAL', 'FORD', 'CR*****.org'),
 ('GLADYS', 'HAMILTON', 'GL*****.org'),
 ('RITA', 'GRAHAM', 'RI*****.org'),
 ('DAWN', 'SULLIVAN', 'DA*****.org'),
 ('CONNIE', 'WALLACE', 'CO*****.org'),
 ('FLORENCE', 'WOODS', 'FL*****.org'),
 ('TRACY', 'COLE', 'TR*****.org'),
 ('EDNA', 'WEST', 'ED*****.org'),
 ('TIFFANY', 'JORDAN', 'TI*****.org'),
 ('CARMEN', 'OWENS', 'CA*****.org'),
 ('ROSA', 'REYNOLDS', 'RO*****.org'),
 ('CINDY', 'FISHER', 'CI*****.org'),
 ('GRACE', 'ELLIS', 'GR*****.org'),
 ('WENDY', 'HARRISON', 'WE*****.org'),
 ('VICTORIA', 'GIBSON', 'VI*****.org'),
 ('EDITH', 'MCDONALD', 'ED*****.org'),
 ('KIM', 'CRUZ', 'KI*****.org'),
 ('SHERRY', 'MARSHALL', 'SH*****.org'),
 ('SYLVIA', 'ORTIZ', 'SY*****.org'),
 ('JOSEPHINE', 'GOMEZ', 'JO*****.org'),
 ('THELMA', 'MURRAY', 'TH*****.org'),
 ('SHANNON', 'FREEMAN', 'SH*****.org'),
 ('ETHEL', 'WEBB', 'ET*****.org'),
 ('ELLEN', 'SIMPSON', 'EL*****.org'),
 ('ELAINE', 'STEVENS', 'EL*****.org'),
 ('MARJORIE', 'TUCKER', 'MA*****.org'),
 ('CARRIE', 'PORTER', 'CA*****.org'),
 ('CHARLOTTE', 'HUNTER', 'CH*****.org'),
 ('MONICA', 'HICKS', 'MO*****.org'),
 ('ESTHER', 'CRAWFORD', 'ES*****.org'),
 ('PAULINE', 'HENRY', 'PA*****.org'),
 ('EMMA', 'BOYD', 'EM*****.org'),
 ('JUANITA', 'MASON', 'JU*****.org'),
 ('ANITA', 'MORALES', 'AN*****.org'),
 ('RHONDA', 'KENNEDY', 'RH*****.org'),
 ('HAZEL', 'WARREN', 'HA*****.org'),
 ('AMBER', 'DIXON', 'AM*****.org'),
 ('EVA', 'RAMOS', 'EV*****.org'),
 ('DEBBIE', 'REYES', 'DE*****.org'),
 ('APRIL', 'BURNS', 'AP*****.org'),
 ('LESLIE', 'GORDON', 'LE*****.org'),
 ('CLARA', 'SHAW', 'CL*****.org'),
 ('LUCILLE', 'HOLMES', 'LU*****.org'),
 ('JAMIE', 'RICE', 'JA*****.org'),
 ('JOANNE', 'ROBERTSON', 'JO*****.org'),
 ('ELEANOR', 'HUNT', 'EL*****.org'),
 ('VALERIE', 'BLACK', 'VA*****.org'),
 ('DANIELLE', 'DANIELS', 'DA*****.org'),
 ('MEGAN', 'PALMER', 'ME*****.org'),
 ('ALICIA', 'MILLS', 'AL*****.org'),
 ('SUZANNE', 'NICHOLS', 'SU*****.org'),
 ('MICHELE', 'GRANT', 'MI*****.org'),
 ('GAIL', 'KNIGHT', 'GA*****.org'),
 ('BERTHA', 'FERGUSON', 'BE*****.org'),
 ('DARLENE', 'ROSE', 'DA*****.org'),
 ('VERONICA', 'STONE', 'VE*****.org'),
 ('JILL', 'HAWKINS', 'JI*****.org'),
 ('ERIN', 'DUNN', 'ER*****.org'),
 ('GERALDINE', 'PERKINS', 'GE*****.org'),
 ('LAUREN', 'HUDSON', 'LA*****.org'),
 ('CATHY', 'SPENCER', 'CA*****.org'),
 ('JOANN', 'GARDNER', 'JO*****.org'),
 ('LORRAINE', 'STEPHENS', 'LO*****.org'),
 ('LYNN', 'PAYNE', 'LY*****.org'),
 ('SALLY', 'PIERCE', 'SA*****.org'),
 ('REGINA', 'BERRY', 'RE*****.org'),
 ('BEATRICE', 'ARNOLD', 'BE*****.org'),
 ('DOLORES', 'WAGNER', 'DO*****.org'),
 ('BERNICE', 'WILLIS', 'BE*****.org'),
 ('AUDREY', 'RAY', 'AU*****.org'),
 ('YVONNE', 'WATKINS', 'YV*****.org'),
 ('ANNETTE', 'OLSON', 'AN*****.org'),
 ('JUNE', 'CARROLL', 'JU*****.org'),
 ('SAMANTHA', 'DUNCAN', 'SA*****.org'),
 ('MARION', 'SNYDER', 'MA*****.org'),
 ('DANA', 'HART', 'DA*****.org'),
 ('STACY', 'CUNNINGHAM', 'ST*****.org'),
 ('ANA', 'BRADLEY', 'AN*****.org'),
 ('RENEE', 'LANE', 'RE*****.org'),
 ('IDA', 'ANDREWS', 'ID*****.org'),
 ('VIVIAN', 'RUIZ', 'VI*****.org'),
 ('ROBERTA', 'HARPER', 'RO*****.org'),
 ('HOLLY', 'FOX', 'HO*****.org'),
 ('BRITTANY', 'RILEY', 'BR*****.org'),
 ('MELANIE', 'ARMSTRONG', 'ME*****.org'),
 ('LORETTA', 'CARPENTER', 'LO*****.org'),
 ('YOLANDA', 'WEAVER', 'YO*****.org'),
 ('JEANETTE', 'GREENE', 'JE*****.org'),
 ('LAURIE', 'LAWRENCE', 'LA*****.org'),
 ('KATIE', 'ELLIOTT', 'KA*****.org'),
 ('KRISTEN', 'CHAVEZ', 'KR*****.org'),
 ('VANESSA', 'SIMS', 'VA*****.org'),
 ('ALMA', 'AUSTIN', 'AL*****.org'),
 ('SUE', 'PETERS', 'SU*****.org'),
 ('ELSIE', 'KELLEY', 'EL*****.org'),
 ('BETH', 'FRANKLIN', 'BE*****.org'),
 ('JEANNE', 'LAWSON', 'JE*****.org'),
 ('VICKI', 'FIELDS', 'VI*****.org'),
 ('CARLA', 'GUTIERREZ', 'CA*****.org'),
 ('TARA', 'RYAN', 'TA*****.org'),
 ('ROSEMARY', 'SCHMIDT', 'RO*****.org'),
 ('EILEEN', 'CARR', 'EI*****.org'),
 ('TERRI', 'VASQUEZ', 'TE*****.org'),
 ('GERTRUDE', 'CASTILLO', 'GE*****.org'),
 ('LUCY', 'WHEELER', 'LU*****.org'),
 ('TONYA', 'CHAPMAN', 'TO*****.org'),
 ('ELLA', 'OLIVER', 'EL*****.org'),
 ('STACEY', 'MONTGOMERY', 'ST*****.org'),
 ('WILMA', 'RICHARDS', 'WI*****.org'),
 ('GINA', 'WILLIAMSON', 'GI*****.org'),
 ('KRISTIN', 'JOHNSTON', 'KR*****.org'),
 ('JESSIE', 'BANKS', 'JE*****.org'),
 ('NATALIE', 'MEYER', 'NA*****.org'),
 ('AGNES', 'BISHOP', 'AG*****.org'),
 ('VERA', 'MCCOY', 'VE*****.org'),
 ('WILLIE', 'HOWELL', 'WI*****.org'),
 ('CHARLENE', 'ALVAREZ', 'CH*****.org'),
 ('BESSIE', 'MORRISON', 'BE*****.org'),
 ('DELORES', 'HANSEN', 'DE*****.org'),
 ('MELINDA', 'FERNANDEZ', 'ME*****.org'),
 ('PEARL', 'GARZA', 'PE*****.org'),
 ('ARLENE', 'HARVEY', 'AR*****.org'),
 ('MAUREEN', 'LITTLE', 'MA*****.org'),
 ('COLLEEN', 'BURTON', 'CO*****.org'),
 ('ALLISON', 'STANLEY', 'AL*****.org'),
 ('TAMARA', 'NGUYEN', 'TA*****.org'),
 ('JOY', 'GEORGE', 'JO*****.org'),
 ('GEORGIA', 'JACOBS', 'GE*****.org'),
 ('CONSTANCE', 'REID', 'CO*****.org'),
 ('LILLIE', 'KIM', 'LI*****.org'),
 ('CLAUDIA', 'FULLER', 'CL*****.org'),
 ('JACKIE', 'LYNCH', 'JA*****.org'),
 ('MARCIA', 'DEAN', 'MA*****.org'),
 ('TANYA', 'GILBERT', 'TA*****.org'),
 ('NELLIE', 'GARRETT', 'NE*****.org'),
 ('MINNIE', 'ROMERO', 'MI*****.org'),
 ('MARLENE', 'WELCH', 'MA*****.org'),
 ('GLENDA', 'FRAZIER', 'GL*****.org'),
 ('LYDIA', 'BURKE', 'LY*****.org'),
 ('VIOLA', 'HANSON', 'VI*****.org'),
 ('COURTNEY', 'DAY', 'CO*****.org'),
 ('MARIAN', 'MENDOZA', 'MA*****.org'),
 ('STELLA', 'MORENO', 'ST*****.org'),
 ('CAROLINE', 'BOWMAN', 'CA*****.org'),
 ('DORA', 'MEDINA', 'DO*****.org'),
 ('JO', 'FOWLER', 'JO*****.org'),
 ('VICKIE', 'BREWER', 'VI*****.org'),
 ('MATTIE', 'HOFFMAN', 'MA*****.org'),
 ('TERRY', 'CARLSON', 'TE*****.org'),
 ('MAXINE', 'SILVA', 'MA*****.org'),
 ('IRMA', 'PEARSON', 'IR*****.org'),
 ('MABEL', 'HOLLAND', 'MA*****.org'),
 ('MARSHA', 'DOUGLAS', 'MA*****.org'),
 ('MYRTLE', 'FLEMING', 'MY*****.org'),
 ('LENA', 'JENSEN', 'LE*****.org'),
 ('CHRISTY', 'VARGAS', 'CH*****.org'),
 ('DEANNA', 'BYRD', 'DE*****.org'),
 ('PATSY', 'DAVIDSON', 'PA*****.org'),
 ('HILDA', 'HOPKINS', 'HI*****.org'),
 ('GWENDOLYN', 'MAY', 'GW*****.org'),
 ('JENNIE', 'TERRY', 'JE*****.org'),
 ('NORA', 'HERRERA', 'NO*****.org'),
 ('MARGIE', 'WADE', 'MA*****.org'),
 ('NINA', 'SOTO', 'NI*****.org'),
 ('CASSANDRA', 'WALTERS', 'CA*****.org'),
 ('LEAH', 'CURTIS', 'LE*****.org'),
 ('KAY', 'CALDWELL', 'KA*****.org'),
 ('PRISCILLA', 'LOWE', 'PR*****.org'),
 ('NAOMI', 'JENNINGS', 'NA*****.org'),
 ('CAROLE', 'BARNETT', 'CA*****.org'),
 ('BRANDY', 'GRAVES', 'BR*****.org'),
 ('OLGA', 'JIMENEZ', 'OL*****.org'),
 ('BILLIE', 'HORTON', 'BI*****.org'),
 ('DIANNE', 'SHELTON', 'DI*****.org'),
 ('TRACEY', 'BARRETT', 'TR*****.org'),
 ('LEONA', 'OBRIEN', 'LE*****.org'),
 ('JENNY', 'CASTRO', 'JE*****.org'),
 ('FELICIA', 'SUTTON', 'FE*****.org'),
 ('SONIA', 'GREGORY', 'SO*****.org'),
 ('MIRIAM', 'MCKINNEY', 'MI*****.org'),
 ('VELMA', 'LUCAS', 'VE*****.org'),
 ('BECKY', 'MILES', 'BE*****.org'),
 ('BOBBIE', 'CRAIG', 'BO*****.org'),
 ('VIOLET', 'RODRIQUEZ', 'VI*****.org'),
 ('KRISTINA', 'CHAMBERS', 'KR*****.org'),
 ('TONI', 'HOLT', 'TO*****.org'),
 ('MISTY', 'LAMBERT', 'MI*****.org'),
 ('MAE', 'FLETCHER', 'MA*****.org'),
 ('SHELLY', 'WATTS', 'SH*****.org'),
 ('DAISY', 'BATES', 'DA*****.org'),
 ('RAMONA', 'HALE', 'RA*****.org'),
 ('SHERRI', 'RHODES', 'SH*****.org'),
 ('ERIKA', 'PENA', 'ER*****.org'),
 ('JAMES', 'GANNON', 'JA*****.org'),
 ('JOHN', 'FARNSWORTH', 'JO*****.org'),
 ('ROBERT', 'BAUGHMAN', 'RO*****.org'),
 ('MICHAEL', 'SILVERMAN', 'MI*****.org'),
 ('WILLIAM', 'SATTERFIELD', 'WI*****.org'),
 ('DAVID', 'ROYAL', 'DA*****.org'),
 ('RICHARD', 'MCCRARY', 'RI*****.org'),
 ('CHARLES', 'KOWALSKI', 'CH*****.org'),
 ('JOSEPH', 'JOY', 'JO*****.org'),
 ('THOMAS', 'GRIGSBY', 'TH*****.org'),
 ('CHRISTOPHER', 'GRECO', 'CH*****.org'),
 ('DANIEL', 'CABRAL', 'DA*****.org'),
 ('PAUL', 'TROUT', 'PA*****.org'),
 ('MARK', 'RINEHART', 'MA*****.org'),
 ('DONALD', 'MAHON', 'DO*****.org'),
 ('GEORGE', 'LINTON', 'GE*****.org'),
 ('STEVEN', 'CURLEY', 'ST*****.org'),
 ('EDWARD', 'BAUGH', 'ED*****.org'),
 ('BRIAN', 'WYMAN', 'BR*****.org'),
 ('RONALD', 'WEINER', 'RO*****.org'),
 ('ANTHONY', 'SCHWAB', 'AN*****.org'),
 ('KEVIN', 'SCHULER', 'KE*****.org'),
 ('JASON', 'MORRISSEY', 'JA*****.org'),
 ('MATTHEW', 'MAHAN', 'MA*****.org'),
 ('GARY', 'COY', 'GA*****.org'),
 ('TIMOTHY', 'BUNN', 'TI*****.org'),
 ('JOSE', 'ANDREW', 'JO*****.org'),
 ('LARRY', 'THRASHER', 'LA*****.org'),
 ('JEFFREY', 'SPEAR', 'JE*****.org'),
 ('FRANK', 'WAGGONER', 'FR*****.org'),
 ('SCOTT', 'SHELLEY', 'SC*****.org'),
 ('ERIC', 'ROBERT', 'ER*****.org'),
 ('STEPHEN', 'QUALLS', 'ST*****.org'),
 ('ANDREW', 'PURDY', 'AN*****.org'),
 ('RAYMOND', 'MCWHORTER', 'RA*****.org'),
 ('GREGORY', 'MAULDIN', 'GR*****.org'),
 ('JOSHUA', 'MARK', 'JO*****.org'),
 ('JERRY', 'JORDON', 'JE*****.org'),
 ('DENNIS', 'GILMAN', 'DE*****.org'),
 ('WALTER', 'PERRYMAN', 'WA*****.org'),
 ('PATRICK', 'NEWSOM', 'PA*****.org'),
 ('PETER', 'MENARD', 'PE*****.org'),
 ('HAROLD', 'MARTINO', 'HA*****.org'),
 ('DOUGLAS', 'GRAF', 'DO*****.org'),
 ('HENRY', 'BILLINGSLEY', 'HE*****.org'),
 ('CARL', 'ARTIS', 'CA*****.org'),
 ('ARTHUR', 'SIMPKINS', 'AR*****.org'),
 ('RYAN', 'SALISBURY', 'RY*****.org'),
 ('ROGER', 'QUINTANILLA', 'RO*****.org'),
 ('JOE', 'GILLILAND', 'JO*****.org'),
 ('JUAN', 'FRALEY', 'JU*****.org'),
 ('JACK', 'FOUST', 'JA*****.org'),
 ('ALBERT', 'CROUSE', 'AL*****.org'),
 ('JONATHAN', 'SCARBOROUGH', 'JO*****.org'),
 ('JUSTIN', 'NGO', 'JU*****.org'),
 ('TERRY', 'GRISSOM', 'TE*****.org'),
 ('GERALD', 'FULTZ', 'GE*****.org'),
 ('KEITH', 'RICO', 'KE*****.org'),
 ('SAMUEL', 'MARLOW', 'SA*****.org'),
 ('WILLIE', 'MARKHAM', 'WI*****.org'),
 ('RALPH', 'MADRIGAL', 'RA*****.org'),
 ('LAWRENCE', 'LAWTON', 'LA*****.org'),
 ('NICHOLAS', 'BARFIELD', 'NI*****.org'),
 ('ROY', 'WHITING', 'RO*****.org'),
 ('BENJAMIN', 'VARNEY', 'BE*****.org'),
 ('BRUCE', 'SCHWARZ', 'BR*****.org'),
 ('BRANDON', 'HUEY', 'BR*****.org'),
 ('ADAM', 'GOOCH', 'AD*****.org'),
 ('FRED', 'WHEAT', 'FR*****.org'),
 ('WAYNE', 'TRUONG', 'WA*****.org'),
 ('BILLY', 'POULIN', 'BI*****.org'),
 ('STEVE', 'MACKENZIE', 'ST*****.org'),
 ('LOUIS', 'LEONE', 'LO*****.org'),
 ('JEREMY', 'HURTADO', 'JE*****.org'),
 ('AARON', 'SELBY', 'AA*****.org'),
 ('RANDY', 'GAITHER', 'RA*****.org'),
 ('HOWARD', 'FORTNER', 'HO*****.org'),
 ('EUGENE', 'CULPEPPER', 'EU*****.org'),
 ('CARLOS', 'COUGHLIN', 'CA*****.org'),
 ('RUSSELL', 'BRINSON', 'RU*****.org'),
 ('BOBBY', 'BOUDREAU', 'BO*****.org'),
 ('VICTOR', 'BARKLEY', 'VI*****.org'),
 ('MARTIN', 'BALES', 'MA*****.org'),
 ('ERNEST', 'STEPP', 'ER*****.org'),
 ('PHILLIP', 'HOLM', 'PH*****.org'),
 ('TODD', 'TAN', 'TO*****.org'),
 ('JESSE', 'SCHILLING', 'JE*****.org'),
 ('CRAIG', 'MORRELL', 'CR*****.org'),
 ('ALAN', 'KAHN', 'AL*****.org'),
 ('SHAWN', 'HEATON', 'SH*****.org'),
 ('CLARENCE', 'GAMEZ', 'CL*****.org'),
 ('SEAN', 'DOUGLASS', 'SE*****.org'),
 ('PHILIP', 'CAUSEY', 'PH*****.org'),
 ('CHRIS', 'BROTHERS', 'CH*****.org'),
 ('JOHNNY', 'TURPIN', 'JO*****.org'),
 ('EARL', 'SHANKS', 'EA*****.org'),
 ('JIMMY', 'SCHRADER', 'JI*****.org'),
 ('ANTONIO', 'MEEK', 'AN*****.org'),
 ('DANNY', 'ISOM', 'DA*****.org'),
 ('BRYAN', 'HARDISON', 'BR*****.org'),
 ('TONY', 'CARRANZA', 'TO*****.org'),
 ('LUIS', 'YANEZ', 'LU*****.org'),
 ('MIKE', 'WAY', 'MI*****.org'),
 ('STANLEY', 'SCROGGINS', 'ST*****.org'),
 ('LEONARD', 'SCHOFIELD', 'LE*****.org'),
 ('DALE', 'RATCLIFF', 'DA*****.org'),
 ('MANUEL', 'MURRELL', 'MA*****.org'),
 ('RODNEY', 'MOELLER', 'RO*****.org'),
 ('CURTIS', 'IRBY', 'CU*****.org'),
 ('NORMAN', 'CURRIER', 'NO*****.org'),
 ('ALLEN', 'BUTTERFIELD', 'AL*****.org'),
 ('MARVIN', 'YEE', 'MA*****.org'),
 ('VINCENT', 'RALSTON', 'VI*****.org'),
 ('GLENN', 'PULLEN', 'GL*****.org'),
 ('JEFFERY', 'PINSON', 'JE*****.org'),
 ('TRAVIS', 'ESTEP', 'TR*****.org'),
 ('JEFF', 'EAST', 'JE*****.org'),
 ('CHAD', 'CARBONE', 'CH*****.org'),
 ('JACOB', 'LANCE', 'JA*****.org'),
 ('LEE', 'HAWKS', 'LE*****.org'),
 ('MELVIN', 'ELLINGTON', 'ME*****.org'),
 ('ALFRED', 'CASILLAS', 'AL*****.org'),
 ('KYLE', 'SPURLOCK', 'KY*****.org'),
 ('FRANCIS', 'SIKES', 'FR*****.org'),
 ('BRADLEY', 'MOTLEY', 'BR*****.org'),
 ('JESUS', 'MCCARTNEY', 'JE*****.org'),
 ('HERBERT', 'KRUGER', 'HE*****.org'),
 ('FREDERICK', 'ISBELL', 'FR*****.org'),
 ('RAY', 'HOULE', 'RA*****.org'),
 ('JOEL', 'FRANCISCO', 'JO*****.org'),
 ('EDWIN', 'BURK', 'ED*****.org'),
 ('DON', 'BONE', 'DO*****.org'),
 ('EDDIE', 'TOMLIN', 'ED*****.org'),
 ('RICKY', 'SHELBY', 'RI*****.org'),
 ('TROY', 'QUIGLEY', 'TR*****.org'),
 ('RANDALL', 'NEUMANN', 'RA*****.org'),
 ('BARRY', 'LOVELACE', 'BA*****.org'),
 ('ALEXANDER', 'FENNELL', 'AL*****.org'),
 ('BERNARD', 'COLBY', 'BE*****.org'),
 ('MARIO', 'CHEATHAM', 'MA*****.org'),
 ('LEROY', 'BUSTAMANTE', 'LE*****.org'),
 ('FRANCISCO', 'SKIDMORE', 'FR*****.org'),
 ('MARCUS', 'HIDALGO', 'MA*****.org'),
 ('MICHEAL', 'FORMAN', 'MI*****.org'),
 ('CLIFFORD', 'BOWENS', 'CL*****.org'),
 ('MIGUEL', 'BETANCOURT', 'MI*****.org'),
 ('OSCAR', 'AQUINO', 'OS*****.org'),
 ('JAY', 'ROBB', 'JA*****.org'),
 ('JIM', 'REA', 'JI*****.org'),
 ('TOM', 'MILNER', 'TO*****.org'),
 ('CALVIN', 'MARTEL', 'CA*****.org'),
 ('ALEX', 'GRESHAM', 'AL*****.org'),
 ('JON', 'WILES', 'JO*****.org'),
 ('RONNIE', 'RICKETTS', 'RO*****.org'),
 ('BILL', 'GAVIN', 'BI*****.org'),
 ('LLOYD', 'DOWD', 'LL*****.org'),
 ('TOMMY', 'COLLAZO', 'TO*****.org'),
 ('LEON', 'BOSTIC', 'LE*****.org'),
 ('DEREK', 'BLAKELY', 'DE*****.org'),
 ('WARREN', 'SHERROD', 'WA*****.org'),
 ('DARRELL', 'POWER', 'DA*****.org'),
 ('JEROME', 'KENYON', 'JE*****.org'),
 ('FLOYD', 'GANDY', 'FL*****.org'),
 ('LEO', 'EBERT', 'LE*****.org'),
 ('ALVIN', 'DELOACH', 'AL*****.org'),
 ('TIM', 'CARY', 'TI*****.org'),
 ('WESLEY', 'BULL', 'WE*****.org'),
 ('GORDON', 'ALLARD', 'GO*****.org'),
 ('DEAN', 'SAUER', 'DE*****.org'),
 ('GREG', 'ROBINS', 'GR*****.org'),
 ('JORGE', 'OLIVARES', 'JO*****.org'),
 ('DUSTIN', 'GILLETTE', 'DU*****.org'),
 ('PEDRO', 'CHESTNUT', 'PE*****.org'),
 ('DERRICK', 'BOURQUE', 'DE*****.org'),
 ('DAN', 'PAINE', 'DA*****.org'),
 ('LEWIS', 'LYMAN', 'LE*****.org'),
 ('ZACHARY', 'HITE', 'ZA*****.org'),
 ('COREY', 'HAUSER', 'CO*****.org'),
 ('HERMAN', 'DEVORE', 'HE*****.org'),
 ('VERNON', 'CHAPA', 'VE*****.org'),
 ('ROBERTO', 'VU', 'RO*****.org'),
 ('CLYDE', 'TOBIAS', 'CL*****.org'),
 ('GLEN', 'TALBERT', 'GL*****.org'),
 ('HECTOR', 'POINDEXTER', 'HE*****.org'),
 ('SHANE', 'MILLARD', 'SH*****.org'),
 ('RICARDO', 'MEADOR', 'RI*****.org'),
 ('SAM', 'MCDUFFIE', 'SA*****.org'),
 ('RICK', 'MATTOX', 'RI*****.org'),
 ('LESTER', 'KRAUS', 'LE*****.org'),
 ('BRENT', 'HARKINS', 'BR*****.org'),
 ('RAMON', 'CHOATE', 'RA*****.org'),
 ('CHARLIE', 'BESS', 'CH*****.org'),
 ('TYLER', 'WREN', 'TY*****.org'),
 ('GILBERT', 'SLEDGE', 'GI*****.org'),
 ('GENE', 'SANBORN', 'GE*****.org'),
 ('MARC', 'OUTLAW', 'MA*****.org'),
 ('REGINALD', 'KINDER', 'RE*****.org'),
 ('RUBEN', 'GEARY', 'RU*****.org'),
 ('BRETT', 'CORNWELL', 'BR*****.org'),
 ('ANGEL', 'BARCLAY', 'AN*****.org'),
 ('NATHANIEL', 'ADAM', 'NA*****.org'),
 ('RAFAEL', 'ABNEY', 'RA*****.org'),
 ('LESLIE', 'SEWARD', 'LE*****.org'),
 ('EDGAR', 'RHOADS', 'ED*****.org'),
 ('MILTON', 'HOWLAND', 'MI*****.org'),
 ('RAUL', 'FORTIER', 'RA*****.org'),
 ('CHESTER', 'BENNER', 'CH*****.org'),
 ('CECIL', 'VINES', 'CE*****.org'),
 ('DUANE', 'TUBBS', 'DU*****.org'),
 ('FRANKLIN', 'TROUTMAN', 'FR*****.org'),
 ('ANDRE', 'RAPP', 'AN*****.org'),
 ('ELMER', 'NOE', 'EL*****.org'),
 ('BRAD', 'MCCURDY', 'BR*****.org'),
 ('GABRIEL', 'HARDER', 'GA*****.org'),
 ('RON', 'DELUCA', 'RO*****.org'),
 ('MITCHELL', 'WESTMORELAND', 'MI*****.org'),
 ('ROLAND', 'SOUTH', 'RO*****.org'),
 ('ARNOLD', 'HAVENS', 'AR*****.org'),
 ('HARVEY', 'GUAJARDO', 'HA*****.org'),
 ('JARED', 'ELY', 'JA*****.org'),
 ('ADRIAN', 'CLARY', 'AD*****.org'),
 ('KARL', 'SEAL', 'KA*****.org'),
 ('CORY', 'MEEHAN', 'CO*****.org'),
 ('CLAUDE', 'HERZOG', 'CL*****.org'),
 ('ERIK', 'GUILLEN', 'ER*****.org'),
 ('DARRYL', 'ASHCRAFT', 'DA*****.org'),
 ('JAMIE', 'WAUGH', 'JA*****.org'),
 ('NEIL', 'RENNER', 'NE*****.org'),
 ('JESSIE', 'MILAM', 'JE*****.org'),
 ('JAVIER', 'ELROD', 'JA*****.org'),
 ('FERNANDO', 'CHURCHILL', 'FE*****.org'),
 ('CLINTON', 'BUFORD', 'CL*****.org'),
 ('TED', 'BREAUX', 'TE*****.org'),
 ('MATHEW', 'BOLIN', 'MA*****.org'),
 ('TYRONE', 'ASHER', 'TY*****.org'),
 ('DARREN', 'WINDHAM', 'DA*****.org'),

Create the CTE using the VIEW definition for the CTE body and SELECT from the CTE.

In [6]:
%%sql
-- SHOW CREATE VIEW active_customer;
WITH active_customer_cte AS (
    SELECT `c`.`first_name` AS `first_name`,
        `c`.`last_name` AS `last_name`,
        concat(left(`c`.`email`,2),'*****.',substring_index(`c`.`email`,'.',-(1))) AS `concealed_email` 
    FROM `customer` `c` 
    WHERE (`c`.`active` = 1)
)
SELECT *
FROM active_customer_cte;

 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
584 rows affected.

[('MARY', 'SMITH', 'MA*****.org'),
 ('PATRICIA', 'JOHNSON', 'PA*****.org'),
 ('LINDA', 'KENNEDY', 'LI*****.org'),
 ('BARBARA', 'JONES', 'BA*****.org'),
 ('ELIZABETH', 'BROWN', 'EL*****.org'),
 ('JENNIFER', 'DAVIS', 'JE*****.org'),
 ('MARIA', 'MILLER', 'MA*****.org'),
 ('SUSAN', 'WILSON', 'SU*****.org'),
 ('MARGARET', 'MOORE', 'MA*****.org'),
 ('DOROTHY', 'TAYLOR', 'DO*****.org'),
 ('LISA', 'ANDERSON', 'LI*****.org'),
 ('NANCY', 'THOMAS', 'NA*****.org'),
 ('KAREN', 'JACKSON', 'KA*****.org'),
 ('BETTY', 'WHITE', 'BE*****.org'),
 ('HELEN', 'HARRIS', 'HE*****.org'),
 ('DONNA', 'THOMPSON', 'DO*****.org'),
 ('CAROL', 'GARCIA', 'CA*****.org'),
 ('RUTH', 'MARTINEZ', 'RU*****.org'),
 ('SHARON', 'ROBINSON', 'SH*****.org'),
 ('MICHELLE', 'CLARK', 'MI*****.org'),
 ('LAURA', 'RODRIGUEZ', 'LA*****.org'),
 ('SARAH', 'LEWIS', 'SA*****.org'),
 ('KIMBERLY', 'LEE', 'KI*****.org'),
 ('DEBORAH', 'WALKER', 'DE*****.org'),
 ('JESSICA', 'HALL', 'JE*****.org'),
 ('SHIRLEY', 'ALLEN', 'SH*****.org'),
 ('CYNTHIA', 'YOUNG', 'CY*****.org'),
 ('ANGELA', 'HERNANDEZ', 'AN*****.org'),
 ('MELISSA', 'KING', 'ME*****.org'),
 ('BRENDA', 'WRIGHT', 'BR*****.org'),
 ('AMY', 'LOPEZ', 'AM*****.org'),
 ('ANNA', 'HILL', 'AN*****.org'),
 ('REBECCA', 'SCOTT', 'RE*****.org'),
 ('VIRGINIA', 'GREEN', 'VI*****.org'),
 ('KATHLEEN', 'ADAMS', 'KA*****.org'),
 ('PAMELA', 'BAKER', 'PA*****.org'),
 ('MARTHA', 'GONZALEZ', 'MA*****.org'),
 ('DEBRA', 'NELSON', 'DE*****.org'),
 ('AMANDA', 'CARTER', 'AM*****.org'),
 ('STEPHANIE', 'MITCHELL', 'ST*****.org'),
 ('CAROLYN', 'PEREZ', 'CA*****.org'),
 ('CHRISTINE', 'ROBERTS', 'CH*****.org'),
 ('MARIE', 'TURNER', 'MA*****.org'),
 ('JANET', 'PHILLIPS', 'JA*****.org'),
 ('CATHERINE', 'CAMPBELL', 'CA*****.org'),
 ('FRANCES', 'PARKER', 'FR*****.org'),
 ('ANN', 'EVANS', 'AN*****.org'),
 ('JOYCE', 'EDWARDS', 'JO*****.org'),
 ('DIANE', 'COLLINS', 'DI*****.org'),
 ('ALICE', 'STEWART', 'AL*****.org'),
 ('JULIE', 'SANCHEZ', 'JU*****.org'),
 ('HEATHER', 'MORRIS', 'HE*****.org'),
 ('TERESA', 'ROGERS', 'TE*****.org'),
 ('DORIS', 'REED', 'DO*****.org'),
 ('GLORIA', 'COOK', 'GL*****.org'),
 ('EVELYN', 'MORGAN', 'EV*****.org'),
 ('JEAN', 'BELL', 'JE*****.org'),
 ('CHERYL', 'MURPHY', 'CH*****.org'),
 ('MILDRED', 'BAILEY', 'MI*****.org'),
 ('KATHERINE', 'RIVERA', 'KA*****.org'),
 ('JOAN', 'COOPER', 'JO*****.org'),
 ('ASHLEY', 'RICHARDSON', 'AS*****.org'),
 ('ROSE', 'HOWARD', 'RO*****.org'),
 ('JANICE', 'WARD', 'JA*****.org'),
 ('KELLY', 'TORRES', 'KE*****.org'),
 ('NICOLE', 'PETERSON', 'NI*****.org'),
 ('JUDY', 'GRAY', 'JU*****.org'),
 ('CHRISTINA', 'RAMIREZ', 'CH*****.org'),
 ('KATHY', 'JAMES', 'KA*****.org'),
 ('THERESA', 'WATSON', 'TH*****.org'),
 ('BEVERLY', 'BROOKS', 'BE*****.org'),
 ('DENISE', 'KELLY', 'DE*****.org'),
 ('TAMMY', 'SANDERS', 'TA*****.org'),
 ('IRENE', 'PRICE', 'IR*****.org'),
 ('JANE', 'BENNETT', 'JA*****.org'),
 ('LORI', 'WOOD', 'LO*****.org'),
 ('RACHEL', 'BARNES', 'RA*****.org'),
 ('MARILYN', 'ROSS', 'MA*****.org'),
 ('ANDREA', 'HENDERSON', 'AN*****.org'),
 ('KATHRYN', 'COLEMAN', 'KA*****.org'),
 ('LOUISE', 'JENKINS', 'LO*****.org'),
 ('SARA', 'PERRY', 'SA*****.org'),
 ('ANNE', 'POWELL', 'AN*****.org'),
 ('JACQUELINE', 'LONG', 'JA*****.org'),
 ('WANDA', 'PATTERSON', 'WA*****.org'),
 ('BONNIE', 'HUGHES', 'BO*****.org'),
 ('JULIA', 'FLORES', 'JU*****.org'),
 ('RUBY', 'WASHINGTON', 'RU*****.org'),
 ('LOIS', 'BUTLER', 'LO*****.org'),
 ('TINA', 'SIMMONS', 'TI*****.org'),
 ('PHYLLIS', 'FOSTER', 'PH*****.org'),
 ('NORMA', 'GONZALES', 'NO*****.org'),
 ('PAULA', 'BRYANT', 'PA*****.org'),
 ('DIANA', 'ALEXANDER', 'DI*****.org'),
 ('ANNIE', 'RUSSELL', 'AN*****.org'),
 ('LILLIAN', 'GRIFFIN', 'LI*****.org'),
 ('EMILY', 'DIAZ', 'EM*****.org'),
 ('ROBIN', 'HAYES', 'RO*****.org'),
 ('PEGGY', 'MYERS', 'PE*****.org'),
 ('CRYSTAL', 'FORD', 'CR*****.org'),
 ('GLADYS', 'HAMILTON', 'GL*****.org'),
 ('RITA', 'GRAHAM', 'RI*****.org'),
 ('DAWN', 'SULLIVAN', 'DA*****.org'),
 ('CONNIE', 'WALLACE', 'CO*****.org'),
 ('FLORENCE', 'WOODS', 'FL*****.org'),
 ('TRACY', 'COLE', 'TR*****.org'),
 ('EDNA', 'WEST', 'ED*****.org'),
 ('TIFFANY', 'JORDAN', 'TI*****.org'),
 ('CARMEN', 'OWENS', 'CA*****.org'),
 ('ROSA', 'REYNOLDS', 'RO*****.org'),
 ('CINDY', 'FISHER', 'CI*****.org'),
 ('GRACE', 'ELLIS', 'GR*****.org'),
 ('WENDY', 'HARRISON', 'WE*****.org'),
 ('VICTORIA', 'GIBSON', 'VI*****.org'),
 ('EDITH', 'MCDONALD', 'ED*****.org'),
 ('KIM', 'CRUZ', 'KI*****.org'),
 ('SHERRY', 'MARSHALL', 'SH*****.org'),
 ('SYLVIA', 'ORTIZ', 'SY*****.org'),
 ('JOSEPHINE', 'GOMEZ', 'JO*****.org'),
 ('THELMA', 'MURRAY', 'TH*****.org'),
 ('SHANNON', 'FREEMAN', 'SH*****.org'),
 ('ETHEL', 'WEBB', 'ET*****.org'),
 ('ELLEN', 'SIMPSON', 'EL*****.org'),
 ('ELAINE', 'STEVENS', 'EL*****.org'),
 ('MARJORIE', 'TUCKER', 'MA*****.org'),
 ('CARRIE', 'PORTER', 'CA*****.org'),
 ('CHARLOTTE', 'HUNTER', 'CH*****.org'),
 ('MONICA', 'HICKS', 'MO*****.org'),
 ('ESTHER', 'CRAWFORD', 'ES*****.org'),
 ('PAULINE', 'HENRY', 'PA*****.org'),
 ('EMMA', 'BOYD', 'EM*****.org'),
 ('JUANITA', 'MASON', 'JU*****.org'),
 ('ANITA', 'MORALES', 'AN*****.org'),
 ('RHONDA', 'KENNEDY', 'RH*****.org'),
 ('HAZEL', 'WARREN', 'HA*****.org'),
 ('AMBER', 'DIXON', 'AM*****.org'),
 ('EVA', 'RAMOS', 'EV*****.org'),
 ('DEBBIE', 'REYES', 'DE*****.org'),
 ('APRIL', 'BURNS', 'AP*****.org'),
 ('LESLIE', 'GORDON', 'LE*****.org'),
 ('CLARA', 'SHAW', 'CL*****.org'),
 ('LUCILLE', 'HOLMES', 'LU*****.org'),
 ('JAMIE', 'RICE', 'JA*****.org'),
 ('JOANNE', 'ROBERTSON', 'JO*****.org'),
 ('ELEANOR', 'HUNT', 'EL*****.org'),
 ('VALERIE', 'BLACK', 'VA*****.org'),
 ('DANIELLE', 'DANIELS', 'DA*****.org'),
 ('MEGAN', 'PALMER', 'ME*****.org'),
 ('ALICIA', 'MILLS', 'AL*****.org'),
 ('SUZANNE', 'NICHOLS', 'SU*****.org'),
 ('MICHELE', 'GRANT', 'MI*****.org'),
 ('GAIL', 'KNIGHT', 'GA*****.org'),
 ('BERTHA', 'FERGUSON', 'BE*****.org'),
 ('DARLENE', 'ROSE', 'DA*****.org'),
 ('VERONICA', 'STONE', 'VE*****.org'),
 ('JILL', 'HAWKINS', 'JI*****.org'),
 ('ERIN', 'DUNN', 'ER*****.org'),
 ('GERALDINE', 'PERKINS', 'GE*****.org'),
 ('LAUREN', 'HUDSON', 'LA*****.org'),
 ('CATHY', 'SPENCER', 'CA*****.org'),
 ('JOANN', 'GARDNER', 'JO*****.org'),
 ('LORRAINE', 'STEPHENS', 'LO*****.org'),
 ('LYNN', 'PAYNE', 'LY*****.org'),
 ('SALLY', 'PIERCE', 'SA*****.org'),
 ('REGINA', 'BERRY', 'RE*****.org'),
 ('BEATRICE', 'ARNOLD', 'BE*****.org'),
 ('DOLORES', 'WAGNER', 'DO*****.org'),
 ('BERNICE', 'WILLIS', 'BE*****.org'),
 ('AUDREY', 'RAY', 'AU*****.org'),
 ('YVONNE', 'WATKINS', 'YV*****.org'),
 ('ANNETTE', 'OLSON', 'AN*****.org'),
 ('JUNE', 'CARROLL', 'JU*****.org'),
 ('SAMANTHA', 'DUNCAN', 'SA*****.org'),
 ('MARION', 'SNYDER', 'MA*****.org'),
 ('DANA', 'HART', 'DA*****.org'),
 ('STACY', 'CUNNINGHAM', 'ST*****.org'),
 ('ANA', 'BRADLEY', 'AN*****.org'),
 ('RENEE', 'LANE', 'RE*****.org'),
 ('IDA', 'ANDREWS', 'ID*****.org'),
 ('VIVIAN', 'RUIZ', 'VI*****.org'),
 ('ROBERTA', 'HARPER', 'RO*****.org'),
 ('HOLLY', 'FOX', 'HO*****.org'),
 ('BRITTANY', 'RILEY', 'BR*****.org'),
 ('MELANIE', 'ARMSTRONG', 'ME*****.org'),
 ('LORETTA', 'CARPENTER', 'LO*****.org'),
 ('YOLANDA', 'WEAVER', 'YO*****.org'),
 ('JEANETTE', 'GREENE', 'JE*****.org'),
 ('LAURIE', 'LAWRENCE', 'LA*****.org'),
 ('KATIE', 'ELLIOTT', 'KA*****.org'),
 ('KRISTEN', 'CHAVEZ', 'KR*****.org'),
 ('VANESSA', 'SIMS', 'VA*****.org'),
 ('ALMA', 'AUSTIN', 'AL*****.org'),
 ('SUE', 'PETERS', 'SU*****.org'),
 ('ELSIE', 'KELLEY', 'EL*****.org'),
 ('BETH', 'FRANKLIN', 'BE*****.org'),
 ('JEANNE', 'LAWSON', 'JE*****.org'),
 ('VICKI', 'FIELDS', 'VI*****.org'),
 ('CARLA', 'GUTIERREZ', 'CA*****.org'),
 ('TARA', 'RYAN', 'TA*****.org'),
 ('ROSEMARY', 'SCHMIDT', 'RO*****.org'),
 ('EILEEN', 'CARR', 'EI*****.org'),
 ('TERRI', 'VASQUEZ', 'TE*****.org'),
 ('GERTRUDE', 'CASTILLO', 'GE*****.org'),
 ('LUCY', 'WHEELER', 'LU*****.org'),
 ('TONYA', 'CHAPMAN', 'TO*****.org'),
 ('ELLA', 'OLIVER', 'EL*****.org'),
 ('STACEY', 'MONTGOMERY', 'ST*****.org'),
 ('WILMA', 'RICHARDS', 'WI*****.org'),
 ('GINA', 'WILLIAMSON', 'GI*****.org'),
 ('KRISTIN', 'JOHNSTON', 'KR*****.org'),
 ('JESSIE', 'BANKS', 'JE*****.org'),
 ('NATALIE', 'MEYER', 'NA*****.org'),
 ('AGNES', 'BISHOP', 'AG*****.org'),
 ('VERA', 'MCCOY', 'VE*****.org'),
 ('WILLIE', 'HOWELL', 'WI*****.org'),
 ('CHARLENE', 'ALVAREZ', 'CH*****.org'),
 ('BESSIE', 'MORRISON', 'BE*****.org'),
 ('DELORES', 'HANSEN', 'DE*****.org'),
 ('MELINDA', 'FERNANDEZ', 'ME*****.org'),
 ('PEARL', 'GARZA', 'PE*****.org'),
 ('ARLENE', 'HARVEY', 'AR*****.org'),
 ('MAUREEN', 'LITTLE', 'MA*****.org'),
 ('COLLEEN', 'BURTON', 'CO*****.org'),
 ('ALLISON', 'STANLEY', 'AL*****.org'),
 ('TAMARA', 'NGUYEN', 'TA*****.org'),
 ('JOY', 'GEORGE', 'JO*****.org'),
 ('GEORGIA', 'JACOBS', 'GE*****.org'),
 ('CONSTANCE', 'REID', 'CO*****.org'),
 ('LILLIE', 'KIM', 'LI*****.org'),
 ('CLAUDIA', 'FULLER', 'CL*****.org'),
 ('JACKIE', 'LYNCH', 'JA*****.org'),
 ('MARCIA', 'DEAN', 'MA*****.org'),
 ('TANYA', 'GILBERT', 'TA*****.org'),
 ('NELLIE', 'GARRETT', 'NE*****.org'),
 ('MINNIE', 'ROMERO', 'MI*****.org'),
 ('MARLENE', 'WELCH', 'MA*****.org'),
 ('GLENDA', 'FRAZIER', 'GL*****.org'),
 ('LYDIA', 'BURKE', 'LY*****.org'),
 ('VIOLA', 'HANSON', 'VI*****.org'),
 ('COURTNEY', 'DAY', 'CO*****.org'),
 ('MARIAN', 'MENDOZA', 'MA*****.org'),
 ('STELLA', 'MORENO', 'ST*****.org'),
 ('CAROLINE', 'BOWMAN', 'CA*****.org'),
 ('DORA', 'MEDINA', 'DO*****.org'),
 ('JO', 'FOWLER', 'JO*****.org'),
 ('VICKIE', 'BREWER', 'VI*****.org'),
 ('MATTIE', 'HOFFMAN', 'MA*****.org'),
 ('TERRY', 'CARLSON', 'TE*****.org'),
 ('MAXINE', 'SILVA', 'MA*****.org'),
 ('IRMA', 'PEARSON', 'IR*****.org'),
 ('MABEL', 'HOLLAND', 'MA*****.org'),
 ('MARSHA', 'DOUGLAS', 'MA*****.org'),
 ('MYRTLE', 'FLEMING', 'MY*****.org'),
 ('LENA', 'JENSEN', 'LE*****.org'),
 ('CHRISTY', 'VARGAS', 'CH*****.org'),
 ('DEANNA', 'BYRD', 'DE*****.org'),
 ('PATSY', 'DAVIDSON', 'PA*****.org'),
 ('HILDA', 'HOPKINS', 'HI*****.org'),
 ('GWENDOLYN', 'MAY', 'GW*****.org'),
 ('JENNIE', 'TERRY', 'JE*****.org'),
 ('NORA', 'HERRERA', 'NO*****.org'),
 ('MARGIE', 'WADE', 'MA*****.org'),
 ('NINA', 'SOTO', 'NI*****.org'),
 ('CASSANDRA', 'WALTERS', 'CA*****.org'),
 ('LEAH', 'CURTIS', 'LE*****.org'),
 ('KAY', 'CALDWELL', 'KA*****.org'),
 ('PRISCILLA', 'LOWE', 'PR*****.org'),
 ('NAOMI', 'JENNINGS', 'NA*****.org'),
 ('CAROLE', 'BARNETT', 'CA*****.org'),
 ('BRANDY', 'GRAVES', 'BR*****.org'),
 ('OLGA', 'JIMENEZ', 'OL*****.org'),
 ('BILLIE', 'HORTON', 'BI*****.org'),
 ('DIANNE', 'SHELTON', 'DI*****.org'),
 ('TRACEY', 'BARRETT', 'TR*****.org'),
 ('LEONA', 'OBRIEN', 'LE*****.org'),
 ('JENNY', 'CASTRO', 'JE*****.org'),
 ('FELICIA', 'SUTTON', 'FE*****.org'),
 ('SONIA', 'GREGORY', 'SO*****.org'),
 ('MIRIAM', 'MCKINNEY', 'MI*****.org'),
 ('VELMA', 'LUCAS', 'VE*****.org'),
 ('BECKY', 'MILES', 'BE*****.org'),
 ('BOBBIE', 'CRAIG', 'BO*****.org'),
 ('VIOLET', 'RODRIQUEZ', 'VI*****.org'),
 ('KRISTINA', 'CHAMBERS', 'KR*****.org'),
 ('TONI', 'HOLT', 'TO*****.org'),
 ('MISTY', 'LAMBERT', 'MI*****.org'),
 ('MAE', 'FLETCHER', 'MA*****.org'),
 ('SHELLY', 'WATTS', 'SH*****.org'),
 ('DAISY', 'BATES', 'DA*****.org'),
 ('RAMONA', 'HALE', 'RA*****.org'),
 ('SHERRI', 'RHODES', 'SH*****.org'),
 ('ERIKA', 'PENA', 'ER*****.org'),
 ('JAMES', 'GANNON', 'JA*****.org'),
 ('JOHN', 'FARNSWORTH', 'JO*****.org'),
 ('ROBERT', 'BAUGHMAN', 'RO*****.org'),
 ('MICHAEL', 'SILVERMAN', 'MI*****.org'),
 ('WILLIAM', 'SATTERFIELD', 'WI*****.org'),
 ('DAVID', 'ROYAL', 'DA*****.org'),
 ('RICHARD', 'MCCRARY', 'RI*****.org'),
 ('CHARLES', 'KOWALSKI', 'CH*****.org'),
 ('JOSEPH', 'JOY', 'JO*****.org'),
 ('THOMAS', 'GRIGSBY', 'TH*****.org'),
 ('CHRISTOPHER', 'GRECO', 'CH*****.org'),
 ('DANIEL', 'CABRAL', 'DA*****.org'),
 ('PAUL', 'TROUT', 'PA*****.org'),
 ('MARK', 'RINEHART', 'MA*****.org'),
 ('DONALD', 'MAHON', 'DO*****.org'),
 ('GEORGE', 'LINTON', 'GE*****.org'),
 ('STEVEN', 'CURLEY', 'ST*****.org'),
 ('EDWARD', 'BAUGH', 'ED*****.org'),
 ('BRIAN', 'WYMAN', 'BR*****.org'),
 ('RONALD', 'WEINER', 'RO*****.org'),
 ('ANTHONY', 'SCHWAB', 'AN*****.org'),
 ('KEVIN', 'SCHULER', 'KE*****.org'),
 ('JASON', 'MORRISSEY', 'JA*****.org'),
 ('MATTHEW', 'MAHAN', 'MA*****.org'),
 ('GARY', 'COY', 'GA*****.org'),
 ('TIMOTHY', 'BUNN', 'TI*****.org'),
 ('JOSE', 'ANDREW', 'JO*****.org'),
 ('LARRY', 'THRASHER', 'LA*****.org'),
 ('JEFFREY', 'SPEAR', 'JE*****.org'),
 ('FRANK', 'WAGGONER', 'FR*****.org'),
 ('SCOTT', 'SHELLEY', 'SC*****.org'),
 ('ERIC', 'ROBERT', 'ER*****.org'),
 ('STEPHEN', 'QUALLS', 'ST*****.org'),
 ('ANDREW', 'PURDY', 'AN*****.org'),
 ('RAYMOND', 'MCWHORTER', 'RA*****.org'),
 ('GREGORY', 'MAULDIN', 'GR*****.org'),
 ('JOSHUA', 'MARK', 'JO*****.org'),
 ('JERRY', 'JORDON', 'JE*****.org'),
 ('DENNIS', 'GILMAN', 'DE*****.org'),
 ('WALTER', 'PERRYMAN', 'WA*****.org'),
 ('PATRICK', 'NEWSOM', 'PA*****.org'),
 ('PETER', 'MENARD', 'PE*****.org'),
 ('HAROLD', 'MARTINO', 'HA*****.org'),
 ('DOUGLAS', 'GRAF', 'DO*****.org'),
 ('HENRY', 'BILLINGSLEY', 'HE*****.org'),
 ('CARL', 'ARTIS', 'CA*****.org'),
 ('ARTHUR', 'SIMPKINS', 'AR*****.org'),
 ('RYAN', 'SALISBURY', 'RY*****.org'),
 ('ROGER', 'QUINTANILLA', 'RO*****.org'),
 ('JOE', 'GILLILAND', 'JO*****.org'),
 ('JUAN', 'FRALEY', 'JU*****.org'),
 ('JACK', 'FOUST', 'JA*****.org'),
 ('ALBERT', 'CROUSE', 'AL*****.org'),
 ('JONATHAN', 'SCARBOROUGH', 'JO*****.org'),
 ('JUSTIN', 'NGO', 'JU*****.org'),
 ('TERRY', 'GRISSOM', 'TE*****.org'),
 ('GERALD', 'FULTZ', 'GE*****.org'),
 ('KEITH', 'RICO', 'KE*****.org'),
 ('SAMUEL', 'MARLOW', 'SA*****.org'),
 ('WILLIE', 'MARKHAM', 'WI*****.org'),
 ('RALPH', 'MADRIGAL', 'RA*****.org'),
 ('LAWRENCE', 'LAWTON', 'LA*****.org'),
 ('NICHOLAS', 'BARFIELD', 'NI*****.org'),
 ('ROY', 'WHITING', 'RO*****.org'),
 ('BENJAMIN', 'VARNEY', 'BE*****.org'),
 ('BRUCE', 'SCHWARZ', 'BR*****.org'),
 ('BRANDON', 'HUEY', 'BR*****.org'),
 ('ADAM', 'GOOCH', 'AD*****.org'),
 ('FRED', 'WHEAT', 'FR*****.org'),
 ('WAYNE', 'TRUONG', 'WA*****.org'),
 ('BILLY', 'POULIN', 'BI*****.org'),
 ('STEVE', 'MACKENZIE', 'ST*****.org'),
 ('LOUIS', 'LEONE', 'LO*****.org'),
 ('JEREMY', 'HURTADO', 'JE*****.org'),
 ('AARON', 'SELBY', 'AA*****.org'),
 ('RANDY', 'GAITHER', 'RA*****.org'),
 ('HOWARD', 'FORTNER', 'HO*****.org'),
 ('EUGENE', 'CULPEPPER', 'EU*****.org'),
 ('CARLOS', 'COUGHLIN', 'CA*****.org'),
 ('RUSSELL', 'BRINSON', 'RU*****.org'),
 ('BOBBY', 'BOUDREAU', 'BO*****.org'),
 ('VICTOR', 'BARKLEY', 'VI*****.org'),
 ('MARTIN', 'BALES', 'MA*****.org'),
 ('ERNEST', 'STEPP', 'ER*****.org'),
 ('PHILLIP', 'HOLM', 'PH*****.org'),
 ('TODD', 'TAN', 'TO*****.org'),
 ('JESSE', 'SCHILLING', 'JE*****.org'),
 ('CRAIG', 'MORRELL', 'CR*****.org'),
 ('ALAN', 'KAHN', 'AL*****.org'),
 ('SHAWN', 'HEATON', 'SH*****.org'),
 ('CLARENCE', 'GAMEZ', 'CL*****.org'),
 ('SEAN', 'DOUGLASS', 'SE*****.org'),
 ('PHILIP', 'CAUSEY', 'PH*****.org'),
 ('CHRIS', 'BROTHERS', 'CH*****.org'),
 ('JOHNNY', 'TURPIN', 'JO*****.org'),
 ('EARL', 'SHANKS', 'EA*****.org'),
 ('JIMMY', 'SCHRADER', 'JI*****.org'),
 ('ANTONIO', 'MEEK', 'AN*****.org'),
 ('DANNY', 'ISOM', 'DA*****.org'),
 ('BRYAN', 'HARDISON', 'BR*****.org'),
 ('TONY', 'CARRANZA', 'TO*****.org'),
 ('LUIS', 'YANEZ', 'LU*****.org'),
 ('MIKE', 'WAY', 'MI*****.org'),
 ('STANLEY', 'SCROGGINS', 'ST*****.org'),
 ('LEONARD', 'SCHOFIELD', 'LE*****.org'),
 ('DALE', 'RATCLIFF', 'DA*****.org'),
 ('MANUEL', 'MURRELL', 'MA*****.org'),
 ('RODNEY', 'MOELLER', 'RO*****.org'),
 ('CURTIS', 'IRBY', 'CU*****.org'),
 ('NORMAN', 'CURRIER', 'NO*****.org'),
 ('ALLEN', 'BUTTERFIELD', 'AL*****.org'),
 ('MARVIN', 'YEE', 'MA*****.org'),
 ('VINCENT', 'RALSTON', 'VI*****.org'),
 ('GLENN', 'PULLEN', 'GL*****.org'),
 ('JEFFERY', 'PINSON', 'JE*****.org'),
 ('TRAVIS', 'ESTEP', 'TR*****.org'),
 ('JEFF', 'EAST', 'JE*****.org'),
 ('CHAD', 'CARBONE', 'CH*****.org'),
 ('JACOB', 'LANCE', 'JA*****.org'),
 ('LEE', 'HAWKS', 'LE*****.org'),
 ('MELVIN', 'ELLINGTON', 'ME*****.org'),
 ('ALFRED', 'CASILLAS', 'AL*****.org'),
 ('KYLE', 'SPURLOCK', 'KY*****.org'),
 ('FRANCIS', 'SIKES', 'FR*****.org'),
 ('BRADLEY', 'MOTLEY', 'BR*****.org'),
 ('JESUS', 'MCCARTNEY', 'JE*****.org'),
 ('HERBERT', 'KRUGER', 'HE*****.org'),
 ('FREDERICK', 'ISBELL', 'FR*****.org'),
 ('RAY', 'HOULE', 'RA*****.org'),
 ('JOEL', 'FRANCISCO', 'JO*****.org'),
 ('EDWIN', 'BURK', 'ED*****.org'),
 ('DON', 'BONE', 'DO*****.org'),
 ('EDDIE', 'TOMLIN', 'ED*****.org'),
 ('RICKY', 'SHELBY', 'RI*****.org'),
 ('TROY', 'QUIGLEY', 'TR*****.org'),
 ('RANDALL', 'NEUMANN', 'RA*****.org'),
 ('BARRY', 'LOVELACE', 'BA*****.org'),
 ('ALEXANDER', 'FENNELL', 'AL*****.org'),
 ('BERNARD', 'COLBY', 'BE*****.org'),
 ('MARIO', 'CHEATHAM', 'MA*****.org'),
 ('LEROY', 'BUSTAMANTE', 'LE*****.org'),
 ('FRANCISCO', 'SKIDMORE', 'FR*****.org'),
 ('MARCUS', 'HIDALGO', 'MA*****.org'),
 ('MICHEAL', 'FORMAN', 'MI*****.org'),
 ('CLIFFORD', 'BOWENS', 'CL*****.org'),
 ('MIGUEL', 'BETANCOURT', 'MI*****.org'),
 ('OSCAR', 'AQUINO', 'OS*****.org'),
 ('JAY', 'ROBB', 'JA*****.org'),
 ('JIM', 'REA', 'JI*****.org'),
 ('TOM', 'MILNER', 'TO*****.org'),
 ('CALVIN', 'MARTEL', 'CA*****.org'),
 ('ALEX', 'GRESHAM', 'AL*****.org'),
 ('JON', 'WILES', 'JO*****.org'),
 ('RONNIE', 'RICKETTS', 'RO*****.org'),
 ('BILL', 'GAVIN', 'BI*****.org'),
 ('LLOYD', 'DOWD', 'LL*****.org'),
 ('TOMMY', 'COLLAZO', 'TO*****.org'),
 ('LEON', 'BOSTIC', 'LE*****.org'),
 ('DEREK', 'BLAKELY', 'DE*****.org'),
 ('WARREN', 'SHERROD', 'WA*****.org'),
 ('DARRELL', 'POWER', 'DA*****.org'),
 ('JEROME', 'KENYON', 'JE*****.org'),
 ('FLOYD', 'GANDY', 'FL*****.org'),
 ('LEO', 'EBERT', 'LE*****.org'),
 ('ALVIN', 'DELOACH', 'AL*****.org'),
 ('TIM', 'CARY', 'TI*****.org'),
 ('WESLEY', 'BULL', 'WE*****.org'),
 ('GORDON', 'ALLARD', 'GO*****.org'),
 ('DEAN', 'SAUER', 'DE*****.org'),
 ('GREG', 'ROBINS', 'GR*****.org'),
 ('JORGE', 'OLIVARES', 'JO*****.org'),
 ('DUSTIN', 'GILLETTE', 'DU*****.org'),
 ('PEDRO', 'CHESTNUT', 'PE*****.org'),
 ('DERRICK', 'BOURQUE', 'DE*****.org'),
 ('DAN', 'PAINE', 'DA*****.org'),
 ('LEWIS', 'LYMAN', 'LE*****.org'),
 ('ZACHARY', 'HITE', 'ZA*****.org'),
 ('COREY', 'HAUSER', 'CO*****.org'),
 ('HERMAN', 'DEVORE', 'HE*****.org'),
 ('VERNON', 'CHAPA', 'VE*****.org'),
 ('ROBERTO', 'VU', 'RO*****.org'),
 ('CLYDE', 'TOBIAS', 'CL*****.org'),
 ('GLEN', 'TALBERT', 'GL*****.org'),
 ('HECTOR', 'POINDEXTER', 'HE*****.org'),
 ('SHANE', 'MILLARD', 'SH*****.org'),
 ('RICARDO', 'MEADOR', 'RI*****.org'),
 ('SAM', 'MCDUFFIE', 'SA*****.org'),
 ('RICK', 'MATTOX', 'RI*****.org'),
 ('LESTER', 'KRAUS', 'LE*****.org'),
 ('BRENT', 'HARKINS', 'BR*****.org'),
 ('RAMON', 'CHOATE', 'RA*****.org'),
 ('CHARLIE', 'BESS', 'CH*****.org'),
 ('TYLER', 'WREN', 'TY*****.org'),
 ('GILBERT', 'SLEDGE', 'GI*****.org'),
 ('GENE', 'SANBORN', 'GE*****.org'),
 ('MARC', 'OUTLAW', 'MA*****.org'),
 ('REGINALD', 'KINDER', 'RE*****.org'),
 ('RUBEN', 'GEARY', 'RU*****.org'),
 ('BRETT', 'CORNWELL', 'BR*****.org'),
 ('ANGEL', 'BARCLAY', 'AN*****.org'),
 ('NATHANIEL', 'ADAM', 'NA*****.org'),
 ('RAFAEL', 'ABNEY', 'RA*****.org'),
 ('LESLIE', 'SEWARD', 'LE*****.org'),
 ('EDGAR', 'RHOADS', 'ED*****.org'),
 ('MILTON', 'HOWLAND', 'MI*****.org'),
 ('RAUL', 'FORTIER', 'RA*****.org'),
 ('CHESTER', 'BENNER', 'CH*****.org'),
 ('CECIL', 'VINES', 'CE*****.org'),
 ('DUANE', 'TUBBS', 'DU*****.org'),
 ('FRANKLIN', 'TROUTMAN', 'FR*****.org'),
 ('ANDRE', 'RAPP', 'AN*****.org'),
 ('ELMER', 'NOE', 'EL*****.org'),
 ('BRAD', 'MCCURDY', 'BR*****.org'),
 ('GABRIEL', 'HARDER', 'GA*****.org'),
 ('RON', 'DELUCA', 'RO*****.org'),
 ('MITCHELL', 'WESTMORELAND', 'MI*****.org'),
 ('ROLAND', 'SOUTH', 'RO*****.org'),
 ('ARNOLD', 'HAVENS', 'AR*****.org'),
 ('HARVEY', 'GUAJARDO', 'HA*****.org'),
 ('JARED', 'ELY', 'JA*****.org'),
 ('ADRIAN', 'CLARY', 'AD*****.org'),
 ('KARL', 'SEAL', 'KA*****.org'),
 ('CORY', 'MEEHAN', 'CO*****.org'),
 ('CLAUDE', 'HERZOG', 'CL*****.org'),
 ('ERIK', 'GUILLEN', 'ER*****.org'),
 ('DARRYL', 'ASHCRAFT', 'DA*****.org'),
 ('JAMIE', 'WAUGH', 'JA*****.org'),
 ('NEIL', 'RENNER', 'NE*****.org'),
 ('JESSIE', 'MILAM', 'JE*****.org'),
 ('JAVIER', 'ELROD', 'JA*****.org'),
 ('FERNANDO', 'CHURCHILL', 'FE*****.org'),
 ('CLINTON', 'BUFORD', 'CL*****.org'),
 ('TED', 'BREAUX', 'TE*****.org'),
 ('MATHEW', 'BOLIN', 'MA*****.org'),
 ('TYRONE', 'ASHER', 'TY*****.org'),
 ('DARREN', 'WINDHAM', 'DA*****.org'),

---

## digital_marketing Database

Connect to your AWS RDS instance

In [7]:
%sql mysql://USERNAME:PASSWORD@HOST

Create a database named ```digital_marketing``` on your AWS RDS instance

In [10]:
%%sql
CREATE DATABASE digital_marketing;

 * mysql://USERNAME:PASSWORD@HOST
   mysql://USERNAME:PASSWORD@HOST/DATABASE
1 rows affected.

[]

Connect to the digital_marketing database on AWS RDS

In [11]:
%sql mysql://USERNAME:PASSWORD@HOST/DATABASE

Create a database connection to use for pandas to insert into a table

In [12]:
engine = create_engine('mysql+mysqldb://USERNAME:PASSWORD@HOST/DATABASE')

## Load the employee table

In [14]:
%%sql
CREATE TABLE employee (
    employee_id INT(11) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    office VARCHAR(255)
);

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
0 rows affected.

[]

Directly load digital_marketing_employee.csv from http://bit.ly/digital_marketing_employee into a dataframe.

In [15]:
employee_df = pd.read_csv('http://bit.ly/digital_marketing_employee')

Inspect the dataframe's first 5 rows

In [17]:
employee_df.head()

   employee_id              name        title       office
0            1       Juan Torres      support      Wichita
1            2      Louise Lewis      support    Cleveland
2            3  Evelyn Alexander  salesperson      Chicago
3            4        Ann Barnes   accounting       Dallas
4            5     Aaron Ramirez   accounting  Minneapolis

Insert the dataframe into the employee table

In [18]:
employee_df.to_sql('employee', engine, if_exists = 'replace', index=False)

141

Verify the employee table insert

In [19]:
%%sql
SELECT *
FROM employee;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
141 rows affected.

[(1, 'Juan Torres', 'support', 'Wichita'),
 (2, 'Louise Lewis', 'support', 'Cleveland'),
 (3, 'Evelyn Alexander', 'salesperson', 'Chicago'),
 (4, 'Ann Barnes', 'accounting', 'Dallas'),
 (5, 'Aaron Ramirez', 'accounting', 'Minneapolis'),
 (6, 'Toby Lucas', 'dba', 'Wichita'),
 (7, 'John Conner', 'salesperson', 'Raleigh'),
 (8, 'Leo Gutierrez', 'salesperson', 'Cleveland'),
 (9, 'Diana Campbell', 'hr', 'Dallas'),
 (10, 'Ryan Fletcher', 'salesperson', 'Dallas'),
 (11, 'Robert Todd', 'programmer', 'Minneapolis'),
 (12, 'Michael Simmons', 'support', 'Wichita'),
 (13, 'Janet Edwards', 'support', 'Memphis'),
 (14, 'Kimberly Hall', 'support', 'Chicago'),
 (15, 'Denise Martin', 'hr', 'Dallas'),
 (16, 'Susan Charles', 'dba', 'Nauvoo'),
 (17, 'Dixie Hanson', 'cto', 'Dallas'),
 (18, 'Doris Wilson', 'salesperson', 'Chicago'),
 (19, 'Tina Jefferson', 'salesperson', 'Cleveland'),
 (20, 'Vernon Pittman', 'salesperson', 'Dallas'),
 (21, 'Ellen Lucas', 'programmer', 'Minneapolis'),
 (22, 'Jesse Mitchell', 'hr', 'Minneapolis'),
 (23, 'Robert Long', 'support', 'Wichita'),
 (24, 'Jeffrey Richardson', 'accounting', 'Minneapolis'),
 (25, 'Lillian Jones', 'dba', 'Minneapolis'),
 (26, 'Norma Harris', 'support', 'Wichita'),
 (27, 'Donald Carter', 'salesperson', 'Chicago'),
 (28, 'Marc Greene', 'programmer', 'Raleigh'),
 (29, 'Winifred Walsh', 'salesperson', 'Minneapolis'),
 (30, 'David Fuller', 'dba', 'Minneapolis'),
 (31, 'Julius Ramos', 'salesperson', 'Cleveland'),
 (32, 'Josefina Fernandez', 'salesperson', 'Wichita'),
 (33, 'Frances Griffin', 'salesperson', 'Chicago'),
 (34, 'Bobby French', 'salesperson', 'Minneapolis'),
 (35, 'Peter Nguyen', 'cfo', 'Minneapolis'),
 (36, 'Mary Howard', 'programmer', 'Dallas'),
 (37, 'Timothy Bennett', 'support', 'Minneapolis'),
 (38, 'Dorothy Anderson', 'salesperson', 'Nauvoo'),
 (39, 'Miquel Fishman', 'dba', 'Chicago'),
 (40, 'Joyce Beck', 'salesperson', 'Memphis'),
 (41, 'Terrance Reese', 'salesperson', 'Minneapolis'),
 (42, 'Marian Patrick', 'salesperson', 'Minneapolis'),
 (43, 'Cynthia Bryant', 'support', 'Wichita'),
 (44, 'Randal Hogan', 'salesperson', 'Raleigh'),
 (45, 'Keith Fahy', 'programmer', 'Dallas'),
 (46, 'Spencer Morgan', 'programmer', 'Minneapolis'),
 (47, 'Joann Smith', 'salesperson', 'Memphis'),
 (48, 'Roxana Bissell', 'dba', 'Chicago'),
 (49, 'Kent Jones', 'salesperson', 'Dallas'),
 (50, 'Elizabeth Evans', 'accounting', 'Dallas'),
 (51, 'Ruby Russell', 'support', 'Chicago'),
 (52, 'Julio Holloway', 'cmo', 'Minneapolis'),
 (53, 'Jennifer Moore', 'salesperson', 'Wichita'),
 (54, 'Justin Neace', 'programmer', 'Minneapolis'),
 (55, 'Paula Harrington', 'manager', 'Chicago'),
 (56, 'Raquel Greene', 'salesperson', 'Dallas'),
 (57, 'Beverly Davis', 'support', 'Minneapolis'),
 (58, 'Javier Foster', 'programmer', 'Wichita'),
 (59, 'Gary Selfridge', 'programmer', 'Dallas'),
 (60, 'Amy Miller', 'support', 'Chicago'),
 (61, 'Patti Harper', 'salesperson', 'Wichita'),
 (62, 'Matt Wright', 'manager', 'Minneapolis'),
 (63, 'Tammy Castro', 'salesperson', 'Memphis'),
 (64, 'Carol Rivera', 'salesperson', 'Chicago'),
 (65, 'Elva Garcia', 'dba', 'Memphis'),
 (66, 'Kathryn Barnes', 'salesperson', 'Dallas'),
 (67, 'Rosemary Bowers', 'manager', 'Cleveland'),
 (68, 'Edmund Hines', 'manager', 'Raleigh'),
 (69, 'Luis Vaughn', 'salesperson', 'Dallas'),
 (70, 'Eugene Tiggs', 'dba', 'Chicago'),
 (71, 'Cecil Adkins', 'salesperson', 'Minneapolis'),
 (72, 'Dave Santos', 'ceo', 'Minneapolis'),
 (73, 'Mark Hamilton', 'dba', 'Raleigh'),
 (74, 'Deanna Hayes', 'salesperson', 'Wichita'),
 (75, 'Timmy Henderson', 'salesperson', 'Raleigh'),
 (76, 'Richard Delgado', 'manager', 'Memphis'),
 (77, 'Nancy Porter', 'dba', 'Raleigh'),
 (78, 'Louis Santiago', 'salesperson', 'Wichita'),
 (79, 'Rafael Sandoval', 'salesperson', 'Dallas'),
 (80, 'Judy Thomas', 'support', 'Wichita'),
 (81, 'Eugene Bailey', 'hr', 'Minneapolis'),
 (82, 'Rosie Austin', 'manager', 'Wichita'),
 (83, 'Mary Lopez', 'support', 'Wichita'),
 (84, 'Julie Patterson', 'support', 'Minneapolis'),
 (85, 'Anne Hernandez', 'hr', 'Minneapolis'),
 (86, 'Marilyn Phillips', 'accounting', 'Dallas'),
 (87, 'Harry Gonzales', 'hr', 'Minneapolis'),
 (88, 'Emily Murphy', 'hr', 'Dallas'),
 (89, 'Tyler Copeland', 'salesperson', 'Raleigh'),
 (90, 'Nathan Graves', 'vp', 'Minneapolis'),
 (91, 'Jacqueline Reed', 'vp', 'Dallas'),
 (92, 'Jacqueline Jenkins', 'accounting', 'Minneapolis'),
 (93, 'Mary Baldwin', 'dba', 'Minneapolis'),
 (94, 'Brian Robinson', 'accounting', 'Minneapolis'),
 (95, 'Virginia Butler', 'salesperson', 'Chicago'),
 (96, 'Mary Walker', 'programmer', 'Raleigh'),
 (97, 'Louise Martin', 'programmer', 'Nauvoo'),
 (98, 'Claude Powell', 'salesperson', 'Dallas'),
 (99, 'Douglas Williams', 'dba', 'Memphis'),
 (100, 'Freida Duchesne', 'programmer', 'Raleigh'),
 (101, 'Teresa Foster', 'support', 'Chicago'),
 (102, 'Ada Turner', 'manager', 'Dallas'),
 (103, 'Emily Wilkerson', 'salesperson', 'Minneapolis'),
 (104, 'Steve Woods', 'salesperson', 'Raleigh'),
 (105, 'Alonzo Page', 'salesperson', 'Cleveland'),
 (106, 'Bradley Black', 'salesperson', 'Raleigh'),
 (107, 'Joseph Dixon', 'programmer', 'Dallas'),
 (108, 'Dwight Marin', 'programmer', 'Dallas'),
 (109, 'Ruby Boyd', 'salesperson', 'Minneapolis'),
 (110, 'Anthony Williams', 'support', 'Wichita'),
 (111, 'Richard Morris', 'support', 'Wichita'),
 (112, 'Debra Leung', 'programmer', 'Wichita'),
 (113, 'Eileen Morrow', 'dba', 'Cleveland'),
 (114, 'Veronica Boone', 'salesperson', 'Raleigh'),
 (115, 'Carol Monreal', 'dba', 'Cleveland'),
 (116, 'Christian Reeves', 'salesperson', 'Raleigh'),
 (117, 'Russell Rios', 'salesperson', 'Wichita'),
 (118, 'Deborah Peterson', 'salesperson', 'Chicago'),
 (119, 'Amos Miles', 'salesperson', 'Raleigh'),
 (120, 'Cheryl Ward', 'hr', 'Dallas'),
 (121, 'Christina Terry', 'salesperson', 'Wichita'),
 (122, 'Sammie Cobb', 'dba', 'Chicago'),
 (123, 'Josh Garza', 'programmer', 'Minneapolis'),
 (124, 'Barry Marsh', 'programmer', 'Wichita'),
 (125, 'Ivan Rangel', 'programmer', 'Wichita'),
 (126, 'Santiago Mclaughlin', 'salesperson', 'Dallas'),
 (127, 'Jennifer Brooks', 'hr', 'Minneapolis'),
 (128, 'Stephanie Dawson', 'salesperson', 'Wichita'),
 (129, 'Sandra Fleming', 'salesperson', 'Minneapolis'),
 (130, 'Douglas Cooper', 'hr', 'Minneapolis'),
 (131, 'Rene Gibbs', 'salesperson', 'Dallas'),
 (132, 'Alan Carroll', 'salesperson', 'Minneapolis'),
 (133, 'Laura Baker', 'accounting', 'Minneapolis'),
 (134, 'Lucy Bennett', 'programmer', 'Dallas'),
 (135, 'Pauline Neal', 'dba', 'Raleigh'),
 (136, 'Jack Green', 'salesperson', 'Chicago'),
 (137, 'Adrian Neal', 'salesperson', 'Dallas'),
 (138, 'Jason Wright', 'salesperson', 'Chicago'),
 (139, 'Kathy Garcia', 'salesperson', 'Chicago'),
 (140, 'Keith Hill', 'hr', 'Minneapolis'),
 (141, 'Mildred Welch', 'manager', 'Nauvoo')]

## Load the commission table

In [20]:
%%sql
CREATE TABLE commission (
    commission_id INT(11) PRIMARY KEY,
    salesperson_id BIGINT(20) NOT NULL,
    commission_amount DECIMAL(12,2) NOT NULL,
    commission_date DATE NOT NULL
);

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
0 rows affected.

[]

digital_marketing_commission.csv source: http://bit.ly/digital_marketing_commission

In [21]:
# Turn the CSV file into a Pandas DataFrame
commission_df = pd.read_csv('http://bit.ly/digital_marketing_commission')

In [22]:
# View the DataFrame's content
commission_df.head()

   commission_id  salesperson_id  commission_amount commission_date
0              1              19              87.07      2016-01-01
1              2              38             336.26      2016-01-01
2              3              42             280.89      2016-01-01
3              4              74             193.83      2016-01-01
4              5              79             106.19      2016-01-01

In [23]:
# Load the DataFrame data into the SQL table in the digital_marketing database
commission_df.to_sql('commission', engine, if_exists = 'replace', index=False)

3119

In [24]:
%%sql
SELECT *
FROM commission
LIMIT 500;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
500 rows affected.

[(1, 19, 87.07, '2016-01-01'),
 (2, 38, 336.26, '2016-01-01'),
 (3, 42, 280.89, '2016-01-01'),
 (4, 74, 193.83, '2016-01-01'),
 (5, 79, 106.19, '2016-01-01'),
 (6, 106, 427.67, '2016-01-01'),
 (7, 44, 456.26, '2016-01-04'),
 (8, 69, 149.32, '2016-01-04'),
 (9, 79, 278.61, '2016-01-04'),
 (10, 104, 134.7, '2016-01-04'),
 (11, 44, 207.13, '2016-01-05'),
 (12, 49, 292.02, '2016-01-05'),
 (13, 53, 203.16, '2016-01-05'),
 (14, 64, 200.47, '2016-01-05'),
 (15, 74, 92.5, '2016-01-05'),
 (16, 74, 147.31, '2016-01-05'),
 (17, 104, 418.36, '2016-01-05'),
 (18, 109, 444.32, '2016-01-05'),
 (19, 18, 173.55, '2016-01-06'),
 (20, 27, 101.97, '2016-01-06'),
 (21, 29, 212.32, '2016-01-06'),
 (22, 33, 59.76, '2016-01-06'),
 (23, 34, 443.88, '2016-01-06'),
 (24, 38, 79.85, '2016-01-06'),
 (25, 53, 165.4, '2016-01-06'),
 (26, 95, 91.65, '2016-01-06'),
 (27, 95, 432.29, '2016-01-06'),
 (28, 117, 482.53, '2016-01-06'),
 (29, 129, 425.75, '2016-01-06'),
 (30, 136, 218.36, '2016-01-06'),
 (31, 33, 299.27, '2016-01-07'),
 (32, 40, 312.57, '2016-01-07'),
 (33, 66, 351.44, '2016-01-07'),
 (34, 78, 362.59, '2016-01-07'),
 (35, 79, 282.56, '2016-01-07'),
 (36, 89, 332.16, '2016-01-07'),
 (37, 119, 185.84, '2016-01-07'),
 (38, 10, 497.12, '2016-01-08'),
 (39, 29, 363.23, '2016-01-08'),
 (40, 79, 218.53, '2016-01-08'),
 (41, 116, 348.56, '2016-01-08'),
 (42, 31, 316.11, '2016-01-11'),
 (43, 56, 84.18, '2016-01-11'),
 (44, 66, 101.71, '2016-01-11'),
 (45, 69, 290.85, '2016-01-11'),
 (46, 75, 446.8, '2016-01-11'),
 (47, 78, 177.63, '2016-01-11'),
 (48, 118, 151.56, '2016-01-11'),
 (49, 126, 99.33, '2016-01-11'),
 (50, 126, 339.93, '2016-01-11'),
 (51, 18, 390.25, '2016-01-12'),
 (52, 47, 373.09, '2016-01-12'),
 (53, 105, 465.09, '2016-01-12'),
 (54, 114, 434.3, '2016-01-12'),
 (55, 129, 234.62, '2016-01-12'),
 (56, 38, 369.24, '2016-01-13'),
 (57, 40, 234.13, '2016-01-13'),
 (58, 42, 320.78, '2016-01-13'),
 (59, 66, 427.6, '2016-01-13'),
 (60, 69, 453.06, '2016-01-13'),
 (61, 69, 182.61, '2016-01-13'),
 (62, 114, 324.4, '2016-01-13'),
 (63, 138, 344.85, '2016-01-13'),
 (64, 27, 68.2, '2016-01-14'),
 (65, 42, 58.6, '2016-01-14'),
 (66, 44, 411.92, '2016-01-14'),
 (67, 64, 283.94, '2016-01-14'),
 (68, 10, 111.94, '2016-01-15'),
 (69, 32, 174.71, '2016-01-15'),
 (70, 126, 496.81, '2016-01-15'),
 (71, 132, 395.23, '2016-01-15'),
 (72, 38, 149.12, '2016-01-18'),
 (73, 41, 214.69, '2016-01-18'),
 (74, 41, 98.21, '2016-01-18'),
 (75, 75, 475.3, '2016-01-18'),
 (76, 79, 128.95, '2016-01-18'),
 (77, 103, 260.56, '2016-01-18'),
 (78, 114, 153.07, '2016-01-18'),
 (79, 118, 192.86, '2016-01-18'),
 (80, 128, 412.74, '2016-01-18'),
 (81, 38, 56.85, '2016-01-19'),
 (82, 40, 70.39, '2016-01-19'),
 (83, 136, 310.84, '2016-01-19'),
 (84, 137, 351.47, '2016-01-19'),
 (85, 74, 325.6, '2016-01-20'),
 (86, 136, 115.05, '2016-01-20'),
 (87, 3, 429.5, '2016-01-21'),
 (88, 10, 157.79, '2016-01-21'),
 (89, 103, 361.97, '2016-01-21'),
 (90, 117, 161.3, '2016-01-21'),
 (91, 131, 300.75, '2016-01-21'),
 (92, 132, 421.25, '2016-01-21'),
 (93, 132, 295.82, '2016-01-21'),
 (94, 136, 133.2, '2016-01-21'),
 (95, 32, 237.21, '2016-01-22'),
 (96, 74, 121.62, '2016-01-22'),
 (97, 78, 437.07, '2016-01-22'),
 (98, 79, 118.11, '2016-01-22'),
 (99, 95, 415.0, '2016-01-22'),
 (100, 128, 305.27, '2016-01-22'),
 (101, 128, 185.12, '2016-01-22'),
 (102, 136, 98.47, '2016-01-22'),
 (103, 49, 311.61, '2016-01-25'),
 (104, 61, 146.26, '2016-01-25'),
 (105, 89, 180.3, '2016-01-25'),
 (106, 98, 392.07, '2016-01-25'),
 (107, 128, 373.58, '2016-01-25'),
 (108, 131, 239.5, '2016-01-25'),
 (109, 32, 480.27, '2016-01-26'),
 (110, 42, 242.22, '2016-01-26'),
 (111, 98, 294.93, '2016-01-26'),
 (112, 128, 137.68, '2016-01-26'),
 (113, 131, 450.76, '2016-01-26'),
 (114, 10, 405.15, '2016-01-27'),
 (115, 34, 442.5, '2016-01-27'),
 (116, 105, 227.43, '2016-01-27'),
 (117, 126, 62.26, '2016-01-27'),
 (118, 138, 68.51, '2016-01-27'),
 (119, 49, 80.27, '2016-01-28'),
 (120, 66, 237.95, '2016-01-28'),
 (121, 104, 237.17, '2016-01-28'),
 (122, 27, 61.51, '2016-01-29'),
 (123, 40, 117.33, '2016-01-29'),
 (124, 98, 129.5, '2016-01-29'),
 (125, 105, 345.4, '2016-01-29'),
 (126, 104, 314.74, '2016-02-01'),
 (127, 138, 337.48, '2016-02-01'),
 (128, 29, 258.21, '2016-02-02'),
 (129, 44, 339.8, '2016-02-02'),
 (130, 49, 108.13, '2016-02-02'),
 (131, 61, 362.46, '2016-02-02'),
 (132, 74, 115.95, '2016-02-02'),
 (133, 103, 150.84, '2016-02-02'),
 (134, 114, 238.09, '2016-02-02'),
 (135, 116, 363.88, '2016-02-02'),
 (136, 32, 409.49, '2016-02-03'),
 (137, 44, 133.9, '2016-02-03'),
 (138, 61, 333.86, '2016-02-03'),
 (139, 129, 384.6, '2016-02-03'),
 (140, 139, 435.32, '2016-02-03'),
 (141, 19, 174.68, '2016-02-04'),
 (142, 29, 314.97, '2016-02-04'),
 (143, 31, 265.98, '2016-02-04'),
 (144, 44, 371.78, '2016-02-04'),
 (145, 47, 342.56, '2016-02-04'),
 (146, 56, 252.97, '2016-02-04'),
 (147, 74, 61.59, '2016-02-04'),
 (148, 95, 51.39, '2016-02-04'),
 (149, 114, 181.11, '2016-02-04'),
 (150, 10, 379.04, '2016-02-05'),
 (151, 10, 161.76, '2016-02-05'),
 (152, 40, 228.99, '2016-02-05'),
 (153, 41, 370.74, '2016-02-05'),
 (154, 69, 92.08, '2016-02-05'),
 (155, 74, 56.43, '2016-02-05'),
 (156, 75, 383.22, '2016-02-05'),
 (157, 31, 338.34, '2016-02-08'),
 (158, 75, 400.37, '2016-02-08'),
 (159, 75, 382.65, '2016-02-08'),
 (160, 3, 142.37, '2016-02-09'),
 (161, 8, 148.29, '2016-02-09'),
 (162, 29, 243.34, '2016-02-10'),
 (163, 33, 100.37, '2016-02-10'),
 (164, 47, 85.48, '2016-02-10'),
 (165, 53, 86.63, '2016-02-10'),
 (166, 56, 93.41, '2016-02-10'),
 (167, 56, 327.23, '2016-02-10'),
 (168, 56, 292.94, '2016-02-10'),
 (169, 75, 121.16, '2016-02-10'),
 (170, 103, 146.56, '2016-02-10'),
 (171, 103, 141.61, '2016-02-10'),
 (172, 119, 485.65, '2016-02-10'),
 (173, 131, 117.82, '2016-02-10'),
 (174, 34, 454.16, '2016-02-11'),
 (175, 53, 469.86, '2016-02-11'),
 (176, 63, 206.0, '2016-02-11'),
 (177, 75, 101.12, '2016-02-11'),
 (178, 89, 483.34, '2016-02-11'),
 (179, 126, 257.31, '2016-02-11'),
 (180, 3, 184.74, '2016-02-12'),
 (181, 31, 191.62, '2016-02-12'),
 (182, 49, 214.07, '2016-02-12'),
 (183, 66, 230.52, '2016-02-12'),
 (184, 78, 418.46, '2016-02-12'),
 (185, 95, 336.17, '2016-02-12'),
 (186, 104, 170.09, '2016-02-12'),
 (187, 126, 70.55, '2016-02-12'),
 (188, 126, 409.77, '2016-02-12'),
 (189, 139, 323.68, '2016-02-12'),
 (190, 10, 111.42, '2016-02-15'),
 (191, 49, 70.05, '2016-02-15'),
 (192, 66, 444.79, '2016-02-15'),
 (193, 74, 51.55, '2016-02-15'),
 (194, 116, 325.98, '2016-02-15'),
 (195, 126, 217.05, '2016-02-15'),
 (196, 136, 485.35, '2016-02-15'),
 (197, 20, 478.95, '2016-02-16'),
 (198, 42, 376.77, '2016-02-16'),
 (199, 64, 213.57, '2016-02-16'),
 (200, 66, 163.24, '2016-02-16'),
 (201, 78, 494.41, '2016-02-16'),
 (202, 79, 404.4, '2016-02-16'),
 (203, 104, 183.47, '2016-02-16'),
 (204, 114, 63.76, '2016-02-16'),
 (205, 118, 168.37, '2016-02-16'),
 (206, 121, 209.55, '2016-02-16'),
 (207, 131, 492.47, '2016-02-16'),
 (208, 8, 469.46, '2016-02-17'),
 (209, 40, 388.62, '2016-02-17'),
 (210, 66, 456.66, '2016-02-17'),
 (211, 138, 193.84, '2016-02-17'),
 (212, 53, 54.26, '2016-02-18'),
 (213, 56, 304.57, '2016-02-18'),
 (214, 61, 93.89, '2016-02-18'),
 (215, 69, 353.91, '2016-02-18'),
 (216, 79, 352.21, '2016-02-18'),
 (217, 89, 176.92, '2016-02-18'),
 (218, 103, 459.73, '2016-02-18'),
 (219, 109, 392.81, '2016-02-18'),
 (220, 139, 364.58, '2016-02-18'),
 (221, 42, 336.84, '2016-02-19'),
 (222, 56, 130.49, '2016-02-19'),
 (223, 8, 409.93, '2016-02-22'),
 (224, 32, 177.01, '2016-02-22'),
 (225, 49, 77.15, '2016-02-22'),
 (226, 53, 184.43, '2016-02-22'),
 (227, 56, 377.76, '2016-02-22'),
 (228, 74, 85.19, '2016-02-22'),
 (229, 98, 207.09, '2016-02-22'),
 (230, 109, 173.0, '2016-02-22'),
 (231, 116, 167.09, '2016-02-22'),
 (232, 126, 332.47, '2016-02-22'),
 (233, 128, 466.85, '2016-02-22'),
 (234, 18, 362.21, '2016-02-23'),
 (235, 27, 241.06, '2016-02-23'),
 (236, 47, 225.32, '2016-02-23'),
 (237, 79, 349.24, '2016-02-23'),
 (238, 89, 164.88, '2016-02-23'),
 (239, 106, 312.46, '2016-02-23'),
 (240, 121, 351.84, '2016-02-23'),
 (241, 121, 83.46, '2016-02-23'),
 (242, 126, 206.62, '2016-02-23'),
 (243, 129, 408.32, '2016-02-23'),
 (244, 10, 327.3, '2016-02-24'),
 (245, 10, 438.45, '2016-02-24'),
 (246, 18, 362.71, '2016-02-24'),
 (247, 20, 239.44, '2016-02-24'),
 (248, 27, 130.82, '2016-02-24'),
 (249, 47, 369.43, '2016-02-24'),
 (250, 66, 275.29, '2016-02-24'),
 (251, 69, 322.53, '2016-02-24'),
 (252, 75, 125.56, '2016-02-24'),
 (253, 136, 398.83, '2016-02-24'),
 (254, 33, 349.31, '2016-02-25'),
 (255, 47, 306.84, '2016-02-25'),
 (256, 64, 111.26, '2016-02-25'),
 (257, 69, 117.0, '2016-02-25'),
 (258, 104, 51.63, '2016-02-25'),
 (259, 132, 52.77, '2016-02-25'),
 (260, 20, 431.56, '2016-02-26'),
 (261, 75, 76.58, '2016-02-26'),
 (262, 79, 289.07, '2016-02-26'),
 (263, 105, 259.59, '2016-02-26'),
 (264, 121, 389.11, '2016-02-26'),
 (265, 129, 269.66, '2016-02-26'),
 (266, 10, 335.67, '2016-02-29'),
 (267, 29, 160.91, '2016-02-29'),
 (268, 61, 449.23, '2016-02-29'),
 (269, 103, 147.19, '2016-02-29'),
 (270, 116, 198.1, '2016-02-29'),
 (271, 10, 401.73, '2016-03-01'),
 (272, 32, 338.87, '2016-03-01'),
 (273, 64, 372.15, '2016-03-01'),
 (274, 78, 135.42, '2016-03-01'),
 (275, 89, 227.35, '2016-03-01'),
 (276, 18, 300.06, '2016-03-02'),
 (277, 29, 209.56, '2016-03-02'),
 (278, 34, 443.97, '2016-03-02'),
 (279, 61, 136.98, '2016-03-02'),
 (280, 78, 395.54, '2016-03-02'),
 (281, 132, 241.3, '2016-03-02'),
 (282, 31, 323.93, '2016-03-04'),
 (283, 75, 254.04, '2016-03-04'),
 (284, 121, 333.64, '2016-03-04'),
 (285, 138, 55.51, '2016-03-04'),
 (286, 139, 324.71, '2016-03-04'),
 (287, 7, 495.11, '2016-03-07'),
 (288, 49, 159.05, '2016-03-07'),
 (289, 129, 180.04, '2016-03-07'),
 (290, 10, 295.58, '2016-03-08'),
 (291, 41, 356.27, '2016-03-08'),
 (292, 49, 348.07, '2016-03-08'),
 (293, 66, 387.98, '2016-03-08'),
 (294, 118, 153.25, '2016-03-08'),
 (295, 139, 411.11, '2016-03-08'),
 (296, 8, 259.15, '2016-03-09'),
 (297, 40, 80.04, '2016-03-09'),
 (298, 41, 339.87, '2016-03-09'),
 (299, 53, 208.02, '2016-03-09'),
 (300, 64, 320.17, '2016-03-09'),
 (301, 78, 489.5, '2016-03-09'),
 (302, 79, 84.69, '2016-03-09'),
 (303, 119, 172.44, '2016-03-09'),
 (304, 131, 212.85, '2016-03-09'),
 (305, 20, 338.36, '2016-03-10'),
 (306, 38, 81.33, '2016-03-10'),
 (307, 38, 205.79, '2016-03-10'),
 (308, 40, 302.55, '2016-03-10'),
 (309, 47, 214.82, '2016-03-10'),
 (310, 49, 59.66, '2016-03-10'),
 (311, 66, 498.59, '2016-03-10'),
 (312, 69, 478.06, '2016-03-10'),
 (313, 106, 214.69, '2016-03-10'),
 (314, 114, 241.28, '2016-03-10'),
 (315, 118, 369.1, '2016-03-10'),
 (316, 49, 72.72, '2016-03-11'),
 (317, 69, 340.77, '2016-03-11'),
 (318, 79, 346.98, '2016-03-11'),
 (319, 117, 276.52, '2016-03-11'),
 (320, 126, 156.2, '2016-03-11'),
 (321, 64, 62.5, '2016-03-14'),
 (322, 75, 394.31, '2016-03-14'),
 (323, 78, 140.77, '2016-03-14'),
 (324, 109, 394.51, '2016-03-14'),
 (325, 117, 119.87, '2016-03-14'),
 (326, 139, 65.62, '2016-03-14'),
 (327, 19, 90.99, '2016-03-15'),
 (328, 38, 328.78, '2016-03-15'),
 (329, 47, 147.49, '2016-03-15'),
 (330, 56, 231.99, '2016-03-15'),
 (331, 61, 143.01, '2016-03-15'),
 (332, 79, 108.9, '2016-03-15'),
 (333, 114, 497.52, '2016-03-15'),
 (334, 138, 434.99, '2016-03-15'),
 (335, 29, 492.95, '2016-03-16'),
 (336, 64, 61.87, '2016-03-16'),
 (337, 66, 364.81, '2016-03-16'),
 (338, 104, 403.18, '2016-03-16'),
 (339, 131, 242.86, '2016-03-16'),
 (340, 8, 384.91, '2016-03-17'),
 (341, 71, 371.56, '2016-03-17'),
 (342, 79, 245.99, '2016-03-17'),
 (343, 98, 259.66, '2016-03-17'),
 (344, 104, 296.0, '2016-03-17'),
 (345, 126, 338.46, '2016-03-17'),
 (346, 44, 480.46, '2016-03-18'),
 (347, 66, 155.37, '2016-03-18'),
 (348, 116, 220.46, '2016-03-18'),
 (349, 117, 479.19, '2016-03-18'),
 (350, 31, 63.16, '2016-03-21'),
 (351, 56, 378.22, '2016-03-21'),
 (352, 56, 450.18, '2016-03-21'),
 (353, 89, 330.54, '2016-03-21'),
 (354, 116, 51.85, '2016-03-21'),
 (355, 132, 199.56, '2016-03-21'),
 (356, 3, 169.62, '2016-03-22'),
 (357, 75, 187.22, '2016-03-22'),
 (358, 106, 119.61, '2016-03-22'),
 (359, 10, 275.05, '2016-03-23'),
 (360, 79, 143.56, '2016-03-23'),
 (361, 119, 422.31, '2016-03-23'),
 (362, 128, 161.44, '2016-03-23'),
 (363, 7, 82.34, '2016-03-24'),
 (364, 33, 488.31, '2016-03-24'),
 (365, 79, 181.12, '2016-03-24'),
 (366, 105, 89.04, '2016-03-24'),
 (367, 105, 465.44, '2016-03-24'),
 (368, 118, 426.32, '2016-03-24'),
 (369, 129, 394.46, '2016-03-24'),
 (370, 136, 257.68, '2016-03-24'),
 (371, 8, 444.13, '2016-03-25'),
 (372, 38, 183.06, '2016-03-25'),
 (373, 61, 274.2, '2016-03-25'),
 (374, 95, 349.88, '2016-03-25'),
 (375, 95, 350.05, '2016-03-25'),
 (376, 117, 205.71, '2016-03-25'),
 (377, 132, 246.47, '2016-03-25'),
 (378, 40, 354.21, '2016-03-28'),
 (379, 75, 128.17, '2016-03-28'),
 (380, 98, 360.48, '2016-03-28'),
 (381, 136, 443.35, '2016-03-28'),
 (382, 27, 268.37, '2016-03-29'),
 (383, 40, 466.42, '2016-03-29'),
 (384, 44, 452.18, '2016-03-29'),
 (385, 53, 78.86, '2016-03-29'),
 (386, 53, 330.94, '2016-03-29'),
 (387, 56, 114.78, '2016-03-29'),
 (388, 89, 430.13, '2016-03-29'),
 (389, 118, 406.17, '2016-03-29'),
 (390, 10, 351.92, '2016-03-30'),
 (391, 32, 302.05, '2016-03-30'),
 (392, 33, 339.39, '2016-03-30'),
 (393, 40, 338.88, '2016-03-30'),
 (394, 121, 88.75, '2016-03-30'),
 (395, 132, 345.71, '2016-03-30'),
 (396, 31, 364.13, '2016-03-31'),
 (397, 79, 296.35, '2016-03-31'),
 (398, 109, 445.2, '2016-03-31'),
 (399, 114, 203.56, '2016-03-31'),
 (400, 121, 355.04, '2016-03-31'),
 (401, 138, 402.03, '2016-03-31'),
 (402, 3, 363.53, '2016-04-01'),
 (403, 44, 342.05, '2016-04-01'),
 (404, 116, 214.23, '2016-04-01'),
 (405, 139, 168.01, '2016-04-01'),
 (406, 20, 375.26, '2016-04-04'),
 (407, 29, 103.66, '2016-04-04'),
 (408, 42, 280.53, '2016-04-04'),
 (409, 98, 486.95, '2016-04-04'),
 (410, 20, 78.93, '2016-04-05'),
 (411, 27, 496.6, '2016-04-05'),
 (412, 29, 129.5, '2016-04-05'),
 (413, 103, 494.57, '2016-04-05'),
 (414, 126, 323.52, '2016-04-05'),
 (415, 128, 244.44, '2016-04-05'),
 (416, 27, 71.16, '2016-04-06'),
 (417, 40, 391.91, '2016-04-06'),
 (418, 42, 108.85, '2016-04-06'),
 (419, 63, 194.56, '2016-04-06'),
 (420, 95, 155.65, '2016-04-06'),
 (421, 116, 373.82, '2016-04-06'),
 (422, 116, 108.86, '2016-04-06'),
 (423, 129, 54.64, '2016-04-06'),
 (424, 34, 386.04, '2016-04-07'),
 (425, 89, 424.52, '2016-04-07'),
 (426, 98, 127.16, '2016-04-07'),
 (427, 10, 486.73, '2016-04-08'),
 (428, 69, 383.69, '2016-04-08'),
 (429, 74, 274.21, '2016-04-08'),
 (430, 74, 416.79, '2016-04-08'),
 (431, 117, 433.74, '2016-04-08'),
 (432, 129, 132.25, '2016-04-08'),
 (433, 34, 372.87, '2016-04-11'),
 (434, 41, 195.09, '2016-04-11'),
 (435, 41, 200.41, '2016-04-11'),
 (436, 41, 71.15, '2016-04-11'),
 (437, 53, 358.31, '2016-04-11'),
 (438, 61, 127.66, '2016-04-11'),
 (439, 95, 85.73, '2016-04-11'),
 (440, 29, 371.78, '2016-04-12'),
 (441, 33, 258.05, '2016-04-12'),
 (442, 42, 478.47, '2016-04-12'),
 (443, 47, 209.82, '2016-04-12'),
 (444, 49, 112.5, '2016-04-12'),
 (445, 49, 409.53, '2016-04-12'),
 (446, 49, 367.35, '2016-04-12'),
 (447, 105, 434.65, '2016-04-12'),
 (448, 117, 239.88, '2016-04-12'),
 (449, 138, 450.89, '2016-04-12'),
 (450, 10, 110.87, '2016-04-13'),
 (451, 20, 179.71, '2016-04-13'),
 (452, 34, 468.21, '2016-04-13'),
 (453, 47, 179.87, '2016-04-13'),
 (454, 75, 154.43, '2016-04-13'),
 (455, 98, 111.33, '2016-04-13'),
 (456, 104, 352.12, '2016-04-13'),
 (457, 106, 63.17, '2016-04-13'),
 (458, 117, 339.29, '2016-04-13'),
 (459, 117, 256.77, '2016-04-13'),
 (460, 132, 102.77, '2016-04-13'),
 (461, 40, 216.57, '2016-04-14'),
 (462, 71, 331.3, '2016-04-14'),
 (463, 42, 199.48, '2016-04-15'),
 (464, 47, 424.91, '2016-04-15'),
 (465, 78, 301.98, '2016-04-15'),
 (466, 78, 68.75, '2016-04-15'),
 (467, 98, 153.65, '2016-04-15'),
 (468, 109, 238.93, '2016-04-15'),
 (469, 131, 190.54, '2016-04-15'),
 (470, 10, 471.85, '2016-04-18'),
 (471, 69, 98.05, '2016-04-18'),
 (472, 114, 414.75, '2016-04-18'),
 (473, 29, 480.27, '2016-04-19'),
 (474, 44, 399.61, '2016-04-19'),
 (475, 98, 228.79, '2016-04-19'),
 (476, 114, 121.77, '2016-04-19'),
 (477, 118, 494.42, '2016-04-19'),
 (478, 138, 252.45, '2016-04-19'),
 (479, 20, 204.51, '2016-04-20'),
 (480, 20, 374.06, '2016-04-20'),
 (481, 40, 478.79, '2016-04-20'),
 (482, 63, 212.64, '2016-04-20'),
 (483, 66, 346.13, '2016-04-20'),
 (484, 89, 155.16, '2016-04-20'),
 (485, 105, 267.15, '2016-04-20'),
 (486, 114, 328.43, '2016-04-20'),
 (487, 19, 329.0, '2016-04-21'),
 (488, 40, 50.76, '2016-04-21'),
 (489, 49, 298.91, '2016-04-21'),
 (490, 75, 169.77, '2016-04-21'),
 (491, 89, 292.84, '2016-04-21'),
 (492, 104, 346.56, '2016-04-21'),
 (493, 129, 216.21, '2016-04-21'),
 (494, 41, 127.45, '2016-04-22'),
 (495, 63, 63.4, '2016-04-22'),
 (496, 131, 403.92, '2016-04-22'),
 (497, 33, 133.52, '2016-04-25'),
 (498, 74, 482.57, '2016-04-25'),
 (499, 95, 128.27, '2016-04-25'),
 (500, 104, 202.91, '2016-04-25')]

---
### 1. Improved readability  
A CTE makes it easier to interpret a query compared to using a subquery. 
  
Find employees from the Chicago office who do not have the salesperson title.

Fulfill the query without a CTE.

In [28]:
%%sql
SELECT *
FROM employee
WHERE office = 'Chicago' AND title != 'salesperson'
ORDER BY title;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
9 rows affected.

[(39, 'Miquel Fishman', 'dba', 'Chicago'),
 (48, 'Roxana Bissell', 'dba', 'Chicago'),
 (70, 'Eugene Tiggs', 'dba', 'Chicago'),
 (122, 'Sammie Cobb', 'dba', 'Chicago'),
 (55, 'Paula Harrington', 'manager', 'Chicago'),
 (14, 'Kimberly Hall', 'support', 'Chicago'),
 (51, 'Ruby Russell', 'support', 'Chicago'),
 (60, 'Amy Miller', 'support', 'Chicago'),
 (101, 'Teresa Foster', 'support', 'Chicago')]

Use a CTE to find all employees from the Chicago office. Query from the CTE then filter for employees without the salesperson title. Sort the results by the title.

In [29]:
%%sql
WITH employee_chicago AS (
    SELECT *
    FROM employee
    WHERE office = 'Chicago'
    ORDER BY title
)
SELECT *
FROM employee_chicago
WHERE title != 'salesperson'
ORDER BY title;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
9 rows affected.

[(39, 'Miquel Fishman', 'dba', 'Chicago'),
 (48, 'Roxana Bissell', 'dba', 'Chicago'),
 (70, 'Eugene Tiggs', 'dba', 'Chicago'),
 (122, 'Sammie Cobb', 'dba', 'Chicago'),
 (55, 'Paula Harrington', 'manager', 'Chicago'),
 (14, 'Kimberly Hall', 'support', 'Chicago'),
 (51, 'Ruby Russell', 'support', 'Chicago'),
 (60, 'Amy Miller', 'support', 'Chicago'),
 (101, 'Teresa Foster', 'support', 'Chicago')]

  Replace the CTE with a subquery to create a derived table.

In [30]:
%%sql
SELECT *
FROM (
    SELECT *
    FROM employee
    WHERE office = 'Chicago'
) AS employee_chicago
WHERE title != 'salesperson'
ORDER BY title;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
9 rows affected.

[(39, 'Miquel Fishman', 'dba', 'Chicago'),
 (48, 'Roxana Bissell', 'dba', 'Chicago'),
 (70, 'Eugene Tiggs', 'dba', 'Chicago'),
 (122, 'Sammie Cobb', 'dba', 'Chicago'),
 (55, 'Paula Harrington', 'manager', 'Chicago'),
 (14, 'Kimberly Hall', 'support', 'Chicago'),
 (51, 'Ruby Russell', 'support', 'Chicago'),
 (60, 'Amy Miller', 'support', 'Chicago'),
 (101, 'Teresa Foster', 'support', 'Chicago')]

---
### 2. Nesting  
We can refer to other CTEs within a CTE. Addresses the complexity added when using nested subqueries to create derived tables.

```
WITH cte1 AS (
    SELECT col1, col2
    FROM table1
),
cte2 AS (
    SELECT col1, col2
    FROM cte1
)
SELECT cte1.col2 
FROM cte1 
JOIN cte2
    ON cte1.col1 = cte2.col1;
```

Find the employees from the Chicago office who have dba as their title. Use 2 separate CTEs to 
1. find employees from the Chicago office 
2. filter the Chicago employees to only show those who have dba as their title.

In [34]:
%%sql
WITH employee_chicago AS (
    SELECT *
    FROM employee
    WHERE office = 'Chicago'
),
employee_chicago_dba AS (
    SELECT *
    FROM employee_chicago
    WHERE title = 'dba'
)
SELECT *
FROM employee_chicago_dba;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
4 rows affected.

[(39, 'Miquel Fishman', 'dba', 'Chicago'),
 (48, 'Roxana Bissell', 'dba', 'Chicago'),
 (70, 'Eugene Tiggs', 'dba', 'Chicago'),
 (122, 'Sammie Cobb', 'dba', 'Chicago')]

---
### 3. Use CTEs for year-over-year comparisons  
You can query the same CTE multiple times in the same query.  
  
Compare the annual commission totals for the salespersons from one year to the next. 

Before adding a CTE, construct a GROUP BY query to get the commission totals per salesperson and year. Use the YEAR() date function on the commission_date year column as one of the "grouped" columns.

In [36]:
%%sql
SELECT salesperson_id,
    YEAR(commission_date) AS year,
    SUM(commission_amount) AS commission_total
FROM commission
GROUP BY salesperson_id, 
    year
ORDER BY salesperson_id;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
110 rows affected.

[(3, 2016, 2249.93),
 (3, 2017, 3449.669999999999),
 (7, 2016, 1088.3200000000002),
 (7, 2017, 3197.25),
 (8, 2016, 4514.7300000000005),
 (8, 2017, 5178.189999999999),
 (10, 2016, 9433.58),
 (10, 2017, 8479.05),
 (18, 2016, 5146.929999999999),
 (18, 2017, 6680.49),
 (19, 2016, 2449.0099999999998),
 (19, 2017, 5193.44),
 (20, 2016, 6093.170000000001),
 (20, 2017, 8260.880000000001),
 (27, 2016, 6729.25),
 (27, 2017, 5766.240000000001),
 (29, 2016, 8072.71),
 (29, 2017, 5322.36),
 (31, 2016, 7161.3),
 (31, 2017, 8473.84),
 (32, 2016, 7161.170000000001),
 (32, 2017, 4023.8199999999997),
 (33, 2016, 8475.14),
 (33, 2017, 6672.3),
 (34, 2016, 10736.72),
 (34, 2017, 9928.69),
 (38, 2016, 5277.459999999999),
 (38, 2017, 12010.910000000002),
 (40, 2016, 10377.720000000003),
 (40, 2017, 8539.439999999999),
 (41, 2016, 8366.91),
 (41, 2017, 10219.329999999998),
 (42, 2016, 7436.57),
 (42, 2017, 6456.68),
 (44, 2016, 12870.31),
 (44, 2017, 8595.130000000001),
 (47, 2016, 12417.509999999995),
 (47, 2017, 7724.589999999999),
 (49, 2016, 9485.64),
 (49, 2017, 8679.84),
 (53, 2016, 5310.08),
 (53, 2017, 10967.640000000001),
 (56, 2016, 7465.509999999998),
 (56, 2017, 7289.490000000002),
 (61, 2016, 7889.909999999999),
 (61, 2017, 7740.47),
 (63, 2016, 4629.889999999999),
 (63, 2017, 6906.14),
 (64, 2016, 6737.23),
 (64, 2017, 6468.149999999999),
 (66, 2016, 9799.209999999995),
 (66, 2017, 9433.56),
 (69, 2016, 8159.490000000001),
 (69, 2017, 12570.949999999995),
 (71, 2016, 3985.55),
 (71, 2017, 8443.95),
 (74, 2016, 8302.5),
 (74, 2017, 6218.34),
 (75, 2016, 8922.699999999995),
 (75, 2017, 7426.66),
 (78, 2016, 9266.080000000004),
 (78, 2017, 11423.480000000003),
 (79, 2016, 12216.46),
 (79, 2017, 9055.539999999997),
 (89, 2016, 13186.679999999993),
 (89, 2017, 8177.240000000002),
 (95, 2016, 5471.259999999999),
 (95, 2017, 6813.64),
 (98, 2016, 8651.649999999998),
 (98, 2017, 7272.290000000001),
 (103, 2016, 6057.860000000001),
 (103, 2017, 6294.81),
 (104, 2016, 9981.569999999998),
 (104, 2017, 7655.84),
 (105, 2016, 8387.520000000002),
 (105, 2017, 9782.689999999999),
 (106, 2016, 6041.180000000001),
 (106, 2017, 9387.769999999999),
 (109, 2016, 7347.169999999999),
 (109, 2017, 5791.500000000001),
 (114, 2016, 11530.399999999998),
 (114, 2017, 10651.1),
 (116, 2016, 10873.299999999997),
 (116, 2017, 13856.739999999998),
 (117, 2016, 10888.29),
 (117, 2017, 8226.050000000001),
 (118, 2016, 7289.669999999998),
 (118, 2017, 9265.96),
 (119, 2016, 3917.1500000000005),
 (119, 2017, 4102.66),
 (121, 2016, 8327.769999999999),
 (121, 2017, 10979.07),
 (126, 2016, 7486.749999999999),
 (126, 2017, 7428.74),
 (128, 2016, 7746.910000000001),
 (128, 2017, 12253.439999999999),
 (129, 2016, 8446.109999999999),
 (129, 2017, 5280.570000000001),
 (131, 2016, 7774.819999999999),
 (131, 2017, 11147.380000000001),
 (132, 2016, 6277.41),
 (132, 2017, 10066.97),
 (136, 2016, 12028.569999999998),
 (136, 2017, 8382.179999999998),
 (137, 2016, 2558.3),
 (137, 2017, 698.9300000000001),
 (138, 2016, 9666.24),
 (138, 2017, 7250.48),
 (139, 2016, 5793.49),
 (139, 2017, 6591.31)]

Display the current and previous year commission totals on the same row. Create a CTE to run the aggregate query. SELECT from the CTE twice with a JOIN on salesperson_id to get the results for the current and previous year. Create different table aliases for the same CTE. Add a filter to return where the current year equals the previous year plus 1.

In [39]:
%%sql
WITH commission_year AS (
    SELECT salesperson_id,
        YEAR(commission_date) AS year,
        SUM(commission_amount) AS commission_total
    FROM commission
    GROUP BY salesperson_id, 
        year
)
SELECT 
    current.*,
    previous.*
FROM commission_year current
JOIN commission_year previous 
    ON current.salesperson_id = previous.salesperson_id
WHERE current.year = previous.year + 1
ORDER BY current.salesperson_id;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
55 rows affected.

[(3, 2017, 3449.669999999999, 3, 2016, 2249.93),
 (7, 2017, 3197.25, 7, 2016, 1088.3200000000002),
 (8, 2017, 5178.189999999999, 8, 2016, 4514.7300000000005),
 (10, 2017, 8479.05, 10, 2016, 9433.58),
 (18, 2017, 6680.49, 18, 2016, 5146.929999999999),
 (19, 2017, 5193.44, 19, 2016, 2449.0099999999998),
 (20, 2017, 8260.880000000001, 20, 2016, 6093.170000000001),
 (27, 2017, 5766.240000000001, 27, 2016, 6729.25),
 (29, 2017, 5322.36, 29, 2016, 8072.71),
 (31, 2017, 8473.84, 31, 2016, 7161.3),
 (32, 2017, 4023.8199999999997, 32, 2016, 7161.170000000001),
 (33, 2017, 6672.3, 33, 2016, 8475.14),
 (34, 2017, 9928.69, 34, 2016, 10736.72),
 (38, 2017, 12010.910000000002, 38, 2016, 5277.459999999999),
 (40, 2017, 8539.439999999999, 40, 2016, 10377.720000000003),
 (41, 2017, 10219.329999999998, 41, 2016, 8366.91),
 (42, 2017, 6456.68, 42, 2016, 7436.57),
 (44, 2017, 8595.130000000001, 44, 2016, 12870.31),
 (47, 2017, 7724.589999999999, 47, 2016, 12417.509999999995),
 (49, 2017, 8679.84, 49, 2016, 9485.64),
 (53, 2017, 10967.640000000001, 53, 2016, 5310.08),
 (56, 2017, 7289.490000000002, 56, 2016, 7465.509999999998),
 (61, 2017, 7740.47, 61, 2016, 7889.909999999999),
 (63, 2017, 6906.14, 63, 2016, 4629.889999999999),
 (64, 2017, 6468.149999999999, 64, 2016, 6737.23),
 (66, 2017, 9433.56, 66, 2016, 9799.209999999995),
 (69, 2017, 12570.949999999995, 69, 2016, 8159.490000000001),
 (71, 2017, 8443.95, 71, 2016, 3985.55),
 (74, 2017, 6218.34, 74, 2016, 8302.5),
 (75, 2017, 7426.66, 75, 2016, 8922.699999999995),
 (78, 2017, 11423.480000000003, 78, 2016, 9266.080000000004),
 (79, 2017, 9055.539999999997, 79, 2016, 12216.46),
 (89, 2017, 8177.240000000002, 89, 2016, 13186.679999999993),
 (95, 2017, 6813.64, 95, 2016, 5471.259999999999),
 (98, 2017, 7272.290000000001, 98, 2016, 8651.649999999998),
 (103, 2017, 6294.81, 103, 2016, 6057.860000000001),
 (104, 2017, 7655.84, 104, 2016, 9981.569999999998),
 (105, 2017, 9782.689999999999, 105, 2016, 8387.520000000002),
 (106, 2017, 9387.769999999999, 106, 2016, 6041.180000000001),
 (109, 2017, 5791.500000000001, 109, 2016, 7347.169999999999),
 (114, 2017, 10651.1, 114, 2016, 11530.399999999998),
 (116, 2017, 13856.739999999998, 116, 2016, 10873.299999999997),
 (117, 2017, 8226.050000000001, 117, 2016, 10888.29),
 (118, 2017, 9265.96, 118, 2016, 7289.669999999998),
 (119, 2017, 4102.66, 119, 2016, 3917.1500000000005),
 (121, 2017, 10979.07, 121, 2016, 8327.769999999999),
 (126, 2017, 7428.74, 126, 2016, 7486.749999999999),
 (128, 2017, 12253.439999999999, 128, 2016, 7746.910000000001),
 (129, 2017, 5280.570000000001, 129, 2016, 8446.109999999999),
 (131, 2017, 11147.380000000001, 131, 2016, 7774.819999999999),
 (132, 2017, 10066.97, 132, 2016, 6277.41),
 (136, 2017, 8382.179999999998, 136, 2016, 12028.569999999998),
 (137, 2017, 698.9300000000001, 137, 2016, 2558.3),
 (138, 2017, 7250.48, 138, 2016, 9666.24),
 (139, 2017, 6591.31, 139, 2016, 5793.49)]

Modify the query above to display the salesperson's name.

In [43]:
%%sql
WITH commission_year AS (
    SELECT salesperson_id,
        e.name AS name,
        YEAR(commission_date) AS year,
        FORMAT(SUM(commission_amount),2) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    GROUP BY salesperson_id, 
        year
)
SELECT 
    current.salesperson_id AS salesperson_id,
    current.name AS salesperson_name,
    current.year AS current_year,
    current.commission_total AS current_year_commission_total,
    previous.year AS previous_year,
    previous.commission_total AS previous_year_commission_total
FROM commission_year current
JOIN commission_year previous 
    ON current.salesperson_id = previous.salesperson_id
WHERE current.year = previous.year + 1
ORDER BY current.salesperson_id;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
55 rows affected.

[(3, 'Evelyn Alexander', 2017, '3,449.67', 2016, '2,249.93'),
 (7, 'John Conner', 2017, '3,197.25', 2016, '1,088.32'),
 (8, 'Leo Gutierrez', 2017, '5,178.19', 2016, '4,514.73'),
 (10, 'Ryan Fletcher', 2017, '8,479.05', 2016, '9,433.58'),
 (18, 'Doris Wilson', 2017, '6,680.49', 2016, '5,146.93'),
 (19, 'Tina Jefferson', 2017, '5,193.44', 2016, '2,449.01'),
 (20, 'Vernon Pittman', 2017, '8,260.88', 2016, '6,093.17'),
 (27, 'Donald Carter', 2017, '5,766.24', 2016, '6,729.25'),
 (29, 'Winifred Walsh', 2017, '5,322.36', 2016, '8,072.71'),
 (31, 'Julius Ramos', 2017, '8,473.84', 2016, '7,161.30'),
 (32, 'Josefina Fernandez', 2017, '4,023.82', 2016, '7,161.17'),
 (33, 'Frances Griffin', 2017, '6,672.30', 2016, '8,475.14'),
 (34, 'Bobby French', 2017, '9,928.69', 2016, '10,736.72'),
 (38, 'Dorothy Anderson', 2017, '12,010.91', 2016, '5,277.46'),
 (40, 'Joyce Beck', 2017, '8,539.44', 2016, '10,377.72'),
 (41, 'Terrance Reese', 2017, '10,219.33', 2016, '8,366.91'),
 (42, 'Marian Patrick', 2017, '6,456.68', 2016, '7,436.57'),
 (44, 'Randal Hogan', 2017, '8,595.13', 2016, '12,870.31'),
 (47, 'Joann Smith', 2017, '7,724.59', 2016, '12,417.51'),
 (49, 'Kent Jones', 2017, '8,679.84', 2016, '9,485.64'),
 (53, 'Jennifer Moore', 2017, '10,967.64', 2016, '5,310.08'),
 (56, 'Raquel Greene', 2017, '7,289.49', 2016, '7,465.51'),
 (61, 'Patti Harper', 2017, '7,740.47', 2016, '7,889.91'),
 (63, 'Tammy Castro', 2017, '6,906.14', 2016, '4,629.89'),
 (64, 'Carol Rivera', 2017, '6,468.15', 2016, '6,737.23'),
 (66, 'Kathryn Barnes', 2017, '9,433.56', 2016, '9,799.21'),
 (69, 'Luis Vaughn', 2017, '12,570.95', 2016, '8,159.49'),
 (71, 'Cecil Adkins', 2017, '8,443.95', 2016, '3,985.55'),
 (74, 'Deanna Hayes', 2017, '6,218.34', 2016, '8,302.50'),
 (75, 'Timmy Henderson', 2017, '7,426.66', 2016, '8,922.70'),
 (78, 'Louis Santiago', 2017, '11,423.48', 2016, '9,266.08'),
 (79, 'Rafael Sandoval', 2017, '9,055.54', 2016, '12,216.46'),
 (89, 'Tyler Copeland', 2017, '8,177.24', 2016, '13,186.68'),
 (95, 'Virginia Butler', 2017, '6,813.64', 2016, '5,471.26'),
 (98, 'Claude Powell', 2017, '7,272.29', 2016, '8,651.65'),
 (103, 'Emily Wilkerson', 2017, '6,294.81', 2016, '6,057.86'),
 (104, 'Steve Woods', 2017, '7,655.84', 2016, '9,981.57'),
 (105, 'Alonzo Page', 2017, '9,782.69', 2016, '8,387.52'),
 (106, 'Bradley Black', 2017, '9,387.77', 2016, '6,041.18'),
 (109, 'Ruby Boyd', 2017, '5,791.50', 2016, '7,347.17'),
 (114, 'Veronica Boone', 2017, '10,651.10', 2016, '11,530.40'),
 (116, 'Christian Reeves', 2017, '13,856.74', 2016, '10,873.30'),
 (117, 'Russell Rios', 2017, '8,226.05', 2016, '10,888.29'),
 (118, 'Deborah Peterson', 2017, '9,265.96', 2016, '7,289.67'),
 (119, 'Amos Miles', 2017, '4,102.66', 2016, '3,917.15'),
 (121, 'Christina Terry', 2017, '10,979.07', 2016, '8,327.77'),
 (126, 'Santiago Mclaughlin', 2017, '7,428.74', 2016, '7,486.75'),
 (128, 'Stephanie Dawson', 2017, '12,253.44', 2016, '7,746.91'),
 (129, 'Sandra Fleming', 2017, '5,280.57', 2016, '8,446.11'),
 (131, 'Rene Gibbs', 2017, '11,147.38', 2016, '7,774.82'),
 (132, 'Alan Carroll', 2017, '10,066.97', 2016, '6,277.41'),
 (136, 'Jack Green', 2017, '8,382.18', 2016, '12,028.57'),
 (137, 'Adrian Neal', 2017, '698.93', 2016, '2,558.30'),
 (138, 'Jason Wright', 2017, '7,250.48', 2016, '9,666.24'),
 (139, 'Kathy Garcia', 2017, '6,591.31', 2016, '5,793.49')]

Add the commission total difference between the two years into the SELECT. Sort the results by that difference.

In [50]:
%%sql
WITH commission_year AS (
    SELECT salesperson_id,
        e.name AS name,
        YEAR(commission_date) AS year,
        SUM(commission_amount) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    GROUP BY salesperson_id, 
        year
)
SELECT 
    current.salesperson_id AS salesperson_id,
    current.name AS salesperson_name,
    current.year AS current_year,
    FORMAT(current.commission_total, 2) AS current_year_commission_total,
    previous.year AS previous_year,
    FORMAT(previous.commission_total, 2) AS previous_year_commission_total,
    FORMAT(current.commission_total - previous.commission_total, 2) AS commission_difference
FROM commission_year current
JOIN commission_year previous 
    ON current.salesperson_id = previous.salesperson_id
WHERE current.year = previous.year + 1
ORDER BY current.commission_total - previous.commission_total;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
55 rows affected.

[(89, 'Tyler Copeland', 2017, '8,177.24', 2016, '13,186.68', '-5,009.44'),
 (47, 'Joann Smith', 2017, '7,724.59', 2016, '12,417.51', '-4,692.92'),
 (44, 'Randal Hogan', 2017, '8,595.13', 2016, '12,870.31', '-4,275.18'),
 (136, 'Jack Green', 2017, '8,382.18', 2016, '12,028.57', '-3,646.39'),
 (129, 'Sandra Fleming', 2017, '5,280.57', 2016, '8,446.11', '-3,165.54'),
 (79, 'Rafael Sandoval', 2017, '9,055.54', 2016, '12,216.46', '-3,160.92'),
 (32, 'Josefina Fernandez', 2017, '4,023.82', 2016, '7,161.17', '-3,137.35'),
 (29, 'Winifred Walsh', 2017, '5,322.36', 2016, '8,072.71', '-2,750.35'),
 (117, 'Russell Rios', 2017, '8,226.05', 2016, '10,888.29', '-2,662.24'),
 (138, 'Jason Wright', 2017, '7,250.48', 2016, '9,666.24', '-2,415.76'),
 (104, 'Steve Woods', 2017, '7,655.84', 2016, '9,981.57', '-2,325.73'),
 (74, 'Deanna Hayes', 2017, '6,218.34', 2016, '8,302.50', '-2,084.16'),
 (137, 'Adrian Neal', 2017, '698.93', 2016, '2,558.30', '-1,859.37'),
 (40, 'Joyce Beck', 2017, '8,539.44', 2016, '10,377.72', '-1,838.28'),
 (33, 'Frances Griffin', 2017, '6,672.30', 2016, '8,475.14', '-1,802.84'),
 (109, 'Ruby Boyd', 2017, '5,791.50', 2016, '7,347.17', '-1,555.67'),
 (75, 'Timmy Henderson', 2017, '7,426.66', 2016, '8,922.70', '-1,496.04'),
 (98, 'Claude Powell', 2017, '7,272.29', 2016, '8,651.65', '-1,379.36'),
 (42, 'Marian Patrick', 2017, '6,456.68', 2016, '7,436.57', '-979.89'),
 (27, 'Donald Carter', 2017, '5,766.24', 2016, '6,729.25', '-963.01'),
 (10, 'Ryan Fletcher', 2017, '8,479.05', 2016, '9,433.58', '-954.53'),
 (114, 'Veronica Boone', 2017, '10,651.10', 2016, '11,530.40', '-879.30'),
 (34, 'Bobby French', 2017, '9,928.69', 2016, '10,736.72', '-808.03'),
 (49, 'Kent Jones', 2017, '8,679.84', 2016, '9,485.64', '-805.80'),
 (66, 'Kathryn Barnes', 2017, '9,433.56', 2016, '9,799.21', '-365.65'),
 (64, 'Carol Rivera', 2017, '6,468.15', 2016, '6,737.23', '-269.08'),
 (56, 'Raquel Greene', 2017, '7,289.49', 2016, '7,465.51', '-176.02'),
 (61, 'Patti Harper', 2017, '7,740.47', 2016, '7,889.91', '-149.44'),
 (126, 'Santiago Mclaughlin', 2017, '7,428.74', 2016, '7,486.75', '-58.01'),
 (119, 'Amos Miles', 2017, '4,102.66', 2016, '3,917.15', '185.51'),
 (103, 'Emily Wilkerson', 2017, '6,294.81', 2016, '6,057.86', '236.95'),
 (8, 'Leo Gutierrez', 2017, '5,178.19', 2016, '4,514.73', '663.46'),
 (139, 'Kathy Garcia', 2017, '6,591.31', 2016, '5,793.49', '797.82'),
 (3, 'Evelyn Alexander', 2017, '3,449.67', 2016, '2,249.93', '1,199.74'),
 (31, 'Julius Ramos', 2017, '8,473.84', 2016, '7,161.30', '1,312.54'),
 (95, 'Virginia Butler', 2017, '6,813.64', 2016, '5,471.26', '1,342.38'),
 (105, 'Alonzo Page', 2017, '9,782.69', 2016, '8,387.52', '1,395.17'),
 (18, 'Doris Wilson', 2017, '6,680.49', 2016, '5,146.93', '1,533.56'),
 (41, 'Terrance Reese', 2017, '10,219.33', 2016, '8,366.91', '1,852.42'),
 (118, 'Deborah Peterson', 2017, '9,265.96', 2016, '7,289.67', '1,976.29'),
 (7, 'John Conner', 2017, '3,197.25', 2016, '1,088.32', '2,108.93'),
 (78, 'Louis Santiago', 2017, '11,423.48', 2016, '9,266.08', '2,157.40'),
 (20, 'Vernon Pittman', 2017, '8,260.88', 2016, '6,093.17', '2,167.71'),
 (63, 'Tammy Castro', 2017, '6,906.14', 2016, '4,629.89', '2,276.25'),
 (121, 'Christina Terry', 2017, '10,979.07', 2016, '8,327.77', '2,651.30'),
 (19, 'Tina Jefferson', 2017, '5,193.44', 2016, '2,449.01', '2,744.43'),
 (116, 'Christian Reeves', 2017, '13,856.74', 2016, '10,873.30', '2,983.44'),
 (106, 'Bradley Black', 2017, '9,387.77', 2016, '6,041.18', '3,346.59'),
 (131, 'Rene Gibbs', 2017, '11,147.38', 2016, '7,774.82', '3,372.56'),
 (132, 'Alan Carroll', 2017, '10,066.97', 2016, '6,277.41', '3,789.56'),
 (69, 'Luis Vaughn', 2017, '12,570.95', 2016, '8,159.49', '4,411.46'),
 (71, 'Cecil Adkins', 2017, '8,443.95', 2016, '3,985.55', '4,458.40'),
 (128, 'Stephanie Dawson', 2017, '12,253.44', 2016, '7,746.91', '4,506.53'),
 (53, 'Jennifer Moore', 2017, '10,967.64', 2016, '5,310.08', '5,657.56'),
 (38, 'Dorothy Anderson', 2017, '12,010.91', 2016, '5,277.46', '6,733.45')]

Modify the output to only show the salespeople whose sales went down from year to year.

In [51]:
%%sql
WITH commission_year AS (
    SELECT salesperson_id,
        e.name AS name,
        YEAR(commission_date) AS year,
        SUM(commission_amount) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    GROUP BY salesperson_id, 
        year
)
SELECT 
    current.salesperson_id AS salesperson_id,
    current.name AS salesperson_name,
    current.year AS current_year,
    FORMAT(current.commission_total, 2) AS current_year_commission_total,
    previous.year AS previous_year,
    FORMAT(previous.commission_total, 2) AS previous_year_commission_total,
    FORMAT(current.commission_total - previous.commission_total, 2) AS commission_difference
FROM commission_year current
JOIN commission_year previous 
    ON current.salesperson_id = previous.salesperson_id
WHERE current.year = previous.year + 1 
    AND current.commission_total < previous.commission_total
ORDER BY current.commission_total - previous.commission_total;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
29 rows affected.

[(89, 'Tyler Copeland', 2017, '8,177.24', 2016, '13,186.68', '-5,009.44'),
 (47, 'Joann Smith', 2017, '7,724.59', 2016, '12,417.51', '-4,692.92'),
 (44, 'Randal Hogan', 2017, '8,595.13', 2016, '12,870.31', '-4,275.18'),
 (136, 'Jack Green', 2017, '8,382.18', 2016, '12,028.57', '-3,646.39'),
 (129, 'Sandra Fleming', 2017, '5,280.57', 2016, '8,446.11', '-3,165.54'),
 (79, 'Rafael Sandoval', 2017, '9,055.54', 2016, '12,216.46', '-3,160.92'),
 (32, 'Josefina Fernandez', 2017, '4,023.82', 2016, '7,161.17', '-3,137.35'),
 (29, 'Winifred Walsh', 2017, '5,322.36', 2016, '8,072.71', '-2,750.35'),
 (117, 'Russell Rios', 2017, '8,226.05', 2016, '10,888.29', '-2,662.24'),
 (138, 'Jason Wright', 2017, '7,250.48', 2016, '9,666.24', '-2,415.76'),
 (104, 'Steve Woods', 2017, '7,655.84', 2016, '9,981.57', '-2,325.73'),
 (74, 'Deanna Hayes', 2017, '6,218.34', 2016, '8,302.50', '-2,084.16'),
 (137, 'Adrian Neal', 2017, '698.93', 2016, '2,558.30', '-1,859.37'),
 (40, 'Joyce Beck', 2017, '8,539.44', 2016, '10,377.72', '-1,838.28'),
 (33, 'Frances Griffin', 2017, '6,672.30', 2016, '8,475.14', '-1,802.84'),
 (109, 'Ruby Boyd', 2017, '5,791.50', 2016, '7,347.17', '-1,555.67'),
 (75, 'Timmy Henderson', 2017, '7,426.66', 2016, '8,922.70', '-1,496.04'),
 (98, 'Claude Powell', 2017, '7,272.29', 2016, '8,651.65', '-1,379.36'),
 (42, 'Marian Patrick', 2017, '6,456.68', 2016, '7,436.57', '-979.89'),
 (27, 'Donald Carter', 2017, '5,766.24', 2016, '6,729.25', '-963.01'),
 (10, 'Ryan Fletcher', 2017, '8,479.05', 2016, '9,433.58', '-954.53'),
 (114, 'Veronica Boone', 2017, '10,651.10', 2016, '11,530.40', '-879.30'),
 (34, 'Bobby French', 2017, '9,928.69', 2016, '10,736.72', '-808.03'),
 (49, 'Kent Jones', 2017, '8,679.84', 2016, '9,485.64', '-805.80'),
 (66, 'Kathryn Barnes', 2017, '9,433.56', 2016, '9,799.21', '-365.65'),
 (64, 'Carol Rivera', 2017, '6,468.15', 2016, '6,737.23', '-269.08'),
 (56, 'Raquel Greene', 2017, '7,289.49', 2016, '7,465.51', '-176.02'),
 (61, 'Patti Harper', 2017, '7,740.47', 2016, '7,889.91', '-149.44'),
 (126, 'Santiago Mclaughlin', 2017, '7,428.74', 2016, '7,486.75', '-58.01')]

### 4. Comparing individuals against their own group  

You can use a CTE in the WHERE.  
  
Find all of the salespeople who made at least 2% of the total commissions earned by all salespeople in the entire company for 2017. Reuse the query above to get the commission totals and adding it to a CTE but only include data for 2017. Calculate what is 2 percent of the total commissions earned in the WHERE clause by querying the CTE a second time.

Filter the commision totals query to only include 2017.

In [55]:
%%sql   
SELECT c.salesperson_id,
    e.name AS name,
    SUM(commission_amount) AS commission_total
FROM commission c
JOIN employee e
    ON c.salesperson_id = e.employee_id
WHERE YEAR(commission_date) = 2017
GROUP BY salesperson_id;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
55 rows affected.

[(41, 'Terrance Reese', 10219.329999999998),
 (47, 'Joann Smith', 7724.589999999999),
 (53, 'Jennifer Moore', 10967.640000000001),
 (74, 'Deanna Hayes', 6218.34),
 (116, 'Christian Reeves', 13856.739999999998),
 (128, 'Stephanie Dawson', 12253.439999999999),
 (27, 'Donald Carter', 5766.240000000001),
 (34, 'Bobby French', 9928.69),
 (75, 'Timmy Henderson', 7426.66),
 (79, 'Rafael Sandoval', 9055.539999999997),
 (131, 'Rene Gibbs', 11147.380000000001),
 (139, 'Kathy Garcia', 6591.31),
 (19, 'Tina Jefferson', 5193.44),
 (42, 'Marian Patrick', 6456.68),
 (71, 'Cecil Adkins', 8443.95),
 (33, 'Frances Griffin', 6672.3),
 (38, 'Dorothy Anderson', 12010.910000000002),
 (61, 'Patti Harper', 7740.47),
 (64, 'Carol Rivera', 6468.149999999999),
 (10, 'Ryan Fletcher', 8479.05),
 (40, 'Joyce Beck', 8539.439999999999),
 (56, 'Raquel Greene', 7289.490000000002),
 (63, 'Tammy Castro', 6906.14),
 (69, 'Luis Vaughn', 12570.949999999995),
 (126, 'Santiago Mclaughlin', 7428.74),
 (29, 'Winifred Walsh', 5322.36),
 (49, 'Kent Jones', 8679.84),
 (106, 'Bradley Black', 9387.769999999999),
 (118, 'Deborah Peterson', 9265.96),
 (138, 'Jason Wright', 7250.48),
 (44, 'Randal Hogan', 8595.130000000001),
 (89, 'Tyler Copeland', 8177.240000000002),
 (31, 'Julius Ramos', 8473.84),
 (95, 'Virginia Butler', 6813.64),
 (119, 'Amos Miles', 4102.66),
 (32, 'Josefina Fernandez', 4023.8199999999997),
 (104, 'Steve Woods', 7655.84),
 (98, 'Claude Powell', 7272.290000000001),
 (132, 'Alan Carroll', 10066.97),
 (109, 'Ruby Boyd', 5791.500000000001),
 (117, 'Russell Rios', 8226.050000000001),
 (7, 'John Conner', 3197.25),
 (66, 'Kathryn Barnes', 9433.56),
 (18, 'Doris Wilson', 6680.49),
 (78, 'Louis Santiago', 11423.480000000003),
 (114, 'Veronica Boone', 10651.1),
 (103, 'Emily Wilkerson', 6294.81),
 (121, 'Christina Terry', 10979.07),
 (3, 'Evelyn Alexander', 3449.669999999999),
 (129, 'Sandra Fleming', 5280.570000000001),
 (136, 'Jack Green', 8382.179999999998),
 (105, 'Alonzo Page', 9782.689999999999),
 (20, 'Vernon Pittman', 8260.880000000001),
 (8, 'Leo Gutierrez', 5178.189999999999),
 (137, 'Adrian Neal', 698.9300000000001)]

What is 2% of the commission total?

In [58]:
%%sql
WITH commission_year AS (
    SELECT c.salesperson_id,
        e.name AS name,
        SUM(commission_amount) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    WHERE YEAR(commission_date) = 2017
    GROUP BY salesperson_id
)
SELECT
    SUM(commission_total) * 0.02 AS two_percent_total_commissions
FROM commission_year;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
1 rows affected.

[(434153.8699999998, 8683.077399999996)]

Find all of the salespeople who made at least 2% of the total commissions earned by all salespeople in the entire company for 2017.

In [61]:
%%sql
WITH commission_year AS (
    SELECT c.salesperson_id,
        e.name AS name,
        SUM(commission_amount) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    WHERE YEAR(commission_date) = 2017
    GROUP BY salesperson_id
)
SELECT *
FROM commission_year cy1
WHERE cy1.commission_total > (
    SELECT 
        SUM(commission_total) * 0.02
    FROM commission_year
)
ORDER BY commission_total DESC;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
17 rows affected.

[(116, 'Christian Reeves', 13856.739999999998),
 (69, 'Luis Vaughn', 12570.949999999995),
 (128, 'Stephanie Dawson', 12253.439999999999),
 (38, 'Dorothy Anderson', 12010.910000000002),
 (78, 'Louis Santiago', 11423.480000000003),
 (131, 'Rene Gibbs', 11147.380000000001),
 (121, 'Christina Terry', 10979.07),
 (53, 'Jennifer Moore', 10967.640000000001),
 (114, 'Veronica Boone', 10651.1),
 (41, 'Terrance Reese', 10219.329999999998),
 (132, 'Alan Carroll', 10066.97),
 (34, 'Bobby French', 9928.69),
 (105, 'Alonzo Page', 9782.689999999999),
 (66, 'Kathryn Barnes', 9433.56),
 (106, 'Bradley Black', 9387.769999999999),
 (118, 'Deborah Peterson', 9265.96),
 (79, 'Rafael Sandoval', 9055.539999999997)]

What would the query look like if you used subqueries to create derived tables instead of CTEs?

Subqueries are slower and harder to read. If we had to modify the repeated subqueries, we'd have to update the query in multiple places. What if we wanted to query for 2016?

In [64]:
%%sql
SELECT *
FROM (
    SELECT c.salesperson_id,
        e.name AS name,
        SUM(commission_amount) AS commission_total
    FROM commission c
    JOIN employee e
        ON c.salesperson_id = e.employee_id
    WHERE YEAR(commission_date) = 2017
    GROUP BY salesperson_id
) AS cy1
WHERE commission_total > (
    SELECT SUM(commission_amount) * 0.02
    FROM commission
    WHERE YEAR(commission_date) = 2017
)
ORDER BY commission_total DESC;

   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com
 * mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/digital_marketing
   mysql://admin:***@isba-dev-01.cd2h7smpaebz.us-east-1.rds.amazonaws.com/sakila
17 rows affected.

[(116, 'Christian Reeves', 13856.739999999998),
 (69, 'Luis Vaughn', 12570.949999999995),
 (128, 'Stephanie Dawson', 12253.439999999999),
 (38, 'Dorothy Anderson', 12010.910000000002),
 (78, 'Louis Santiago', 11423.480000000003),
 (131, 'Rene Gibbs', 11147.380000000001),
 (121, 'Christina Terry', 10979.07),
 (53, 'Jennifer Moore', 10967.640000000001),
 (114, 'Veronica Boone', 10651.1),
 (41, 'Terrance Reese', 10219.329999999998),
 (132, 'Alan Carroll', 10066.97),
 (34, 'Bobby French', 9928.69),
 (105, 'Alonzo Page', 9782.689999999999),
 (66, 'Kathryn Barnes', 9433.56),
 (106, 'Bradley Black', 9387.769999999999),
 (118, 'Deborah Peterson', 9265.96),
 (79, 'Rafael Sandoval', 9055.539999999997)]

### As optional practice, rewrite queries using subqueries with CTEs.